In [3]:
import re
import json
import math
import numpy as np
import pandas as pd

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

import sys
sys.path.append("../src")

from hypothesis_benchmark_generator_v2 import classify_with_thresholds

ModuleNotFoundError: No module named 'hypothesis_benchmark_generator_v2'

In [ ]:
import os
print(os.getcwd())

e:\ClimateTwinIndia\experiments\experiment_05_derivation

In [ ]:
from pathlib import Path

for p in Path("../..").rglob("hypothesis_benchmark_generator_v2.py"):
    print(p.resolve())

E:\ClimateTwinIndia\src\hypothesis_benchmark_generator_v2.py

In [ ]:
import sys

sys.path.append(r"E:\ClimateTwinIndia\src")

from hypothesis_benchmark_generator_v2 import classify_with_thresholds

print("Imported successfully!")

Imported successfully!

In [ ]:
import json
import pandas as pd

with open("../../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

rows=[]

for q in bench["questions"]:

    rows.append({

        "id":q["id"],
        "GT_Decision":q["context"]["decision"],
        "metrics":q["context"]["metrics"],
        "protocol":q["context"]["protocol"]

    })

gt=pd.DataFrame(rows)

gt.head()

,id,GT_Decision,metrics,protocol
0,HYP-001,SUPPORTED,"{'min_yearly_mean_abs_anomaly': 0.7789, 'min_f...",{'subcategory': 'persistent_regional_anomaly_v...
1,HYP-002,SUPPORTED,"{'min_yearly_mean_abs_anomaly': 1.6805, 'min_f...",{'subcategory': 'persistent_regional_anomaly_v...
2,HYP-003,SUPPORTED,"{'min_yearly_mean_abs_anomaly': 0.9982, 'min_f...",{'subcategory': 'persistent_regional_anomaly_v...
3,HYP-004,SUPPORTED,"{'min_yearly_mean_abs_anomaly': 1.1584, 'min_f...",{'subcategory': 'persistent_regional_anomaly_v...
4,HYP-005,SUPPORTED,"{'min_yearly_mean_abs_anomaly': 0.8405, 'min_f...",{'subcategory': 'persistent_regional_anomaly_v...

In [ ]:
import re

with open(
    "raw_outputs/deepseek_derivation.txt",
    "r",
    encoding="utf8"
) as f:

    text=f.read()

ids=re.findall(r"(HYP-\d+)",text)

m1=re.findall(r"Metric_1\s*=\s*([-+]?\d*\.?\d+)",text)
m2=re.findall(r"Metric_2\s*=\s*([-+]?\d*\.?\d+)",text)
m3=re.findall(r"Metric_3\s*=\s*([-+]?\d*\.?\d+)",text)

decisions=re.findall(r"Decision\s*=\s*([ABC])",text)

print("IDs:",len(ids))
print("Metric1:",len(m1))
print("Metric2:",len(m2))
print("Metric3:",len(m3))
print("Decision:",len(decisions))

IDs: 0
Metric1: 239
Metric2: 239
Metric3: 239
Decision: 239

In [ ]:
print(text[:1500])

Derived Values
Metric_1 = 0.7789
Metric_2 = 0.4444
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 1.6805
Metric_2 = 0.8889
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.9982
Metric_2 = 0.6667
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 1.1584
Metric_2 = 0.7778
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.8405
Metric_2 = 0.6667
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 1.0254
Metric_2 = 0.5556
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.7502
Metric_2 = 0.5556
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.9184
Metric_2 = 0.5556
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 1.0246
Metric_2 = 0.5556
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.9352
Metric_2 = 0.5556
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 1.0972
Metric_2 = 0.4444
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.8655
Metric_2 = 0.4444
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.7658
Metric_2 = 0.7778
Metric_3 = 1.0000
Decision = A

Derived Values
Metric_1 = 0.1953
Metric_2 = 0.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.3021
Metric_2 = 0.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.3525
Metric_2 = 0.1111
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2328
Metric_2 = 0.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.3349
Metric_2 = 0.0000
Metric_3 = 1.0000
Decision = B

Derive

In [ ]:
print(text[-1500:])

on = B

Derived Values
Metric_1 = 0.2145
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2878
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2685
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2557
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.4970
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.6416
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4975
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7299
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4774
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.5837
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7539
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7970
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7623
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4724
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.5091
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.8326
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4922
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.6410
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

In [ ]:
print(text.count("Derived Values"))
print(text.count("Metric_1"))
print(text.count("Metric_2"))
print(text.count("Metric_3"))
print(text.count("Decision"))

239
239
239
239
239

In [ ]:
print(text[-2000:])

sion = B

Derived Values
Metric_1 = 0.3415
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.4156
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.1910
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.3641
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.3951
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.3697
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2145
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2878
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2685
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.2557
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = B

Derived Values
Metric_1 = 0.4970
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.6416
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4975
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7299
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4774
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.5837
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7539
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7970
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.7623
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4724
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.5091
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.8326
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.4922
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

Derived Values
Metric_1 = 0.6410
Metric_2 = 1.0000
Metric_3 = 1.0000
Decision = C

In [ ]:
import json
import re

import numpy as np
import pandas as pd

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

from hypothesis_benchmark_generator_v2 import classify_with_thresholds

In [ ]:
with open("../../benchmark/ClimateTwinBench_Hypothesis_V2.json") as f:
    benchmark=json.load(f)

questions=benchmark["questions"]

print(len(questions))

240

In [ ]:
import json
import re
import pandas as pd
import numpy as np

In [ ]:
with open("../../benchmark/ClimateTwinBench_Hypothesis_V2.json", "r") as f:
    benchmark = json.load(f)

questions = benchmark["questions"]

print("Questions:", len(questions))

Questions: 240

In [ ]:
with open("raw_outputs/deepseek_derivation.txt", "r", encoding="utf8") as f:
    text = f.read()

print(len(text))

19361

In [ ]:
m1 = re.findall(r"Metric_1\s*=\s*([-+]?\d*\.?\d+)", text)
m2 = re.findall(r"Metric_2\s*=\s*([-+]?\d*\.?\d+)", text)
m3 = re.findall(r"Metric_3\s*=\s*([-+]?\d*\.?\d+)", text)
decisions = re.findall(r"Decision\s*=\s*([ABC])", text)

print("Metric1:", len(m1))
print("Metric2:", len(m2))
print("Metric3:", len(m3))
print("Decision:", len(decisions))

Metric1: 239
Metric2: 239
Metric3: 239
Decision: 239

In [ ]:
with open("raw_outputs/deepseek_derivation.txt", "r", encoding="utf8") as f:
    text = f.read()

print("Characters:", len(text))

Characters: 19361

In [ ]:
m1 = re.findall(
    r"Metric_1\s*=\s*([-+]?\d*\.?\d+)",
    text
)

m2 = re.findall(
    r"Metric_2\s*=\s*([-+]?\d*\.?\d+)",
    text
)

m3 = re.findall(
    r"Metric_3\s*=\s*([-+]?\d*\.?\d+)",
    text
)

decisions = re.findall(
    r"Decision\s*=\s*([ABC])",
    text
)

print("Metric1 :", len(m1))
print("Metric2 :", len(m2))
print("Metric3 :", len(m3))
print("Decision:", len(decisions))

Metric1 : 239
Metric2 : 239
Metric3 : 239
Decision: 239

In [ ]:
import pprint

pprint.pp(questions[0]["context"])

{'decision': 'SUPPORTED',
 'metrics': {'min_yearly_mean_abs_anomaly': 0.7789,
             'min_fraction_cells_above_p75': 0.4444,
             'min_yearly_mean_completeness': 1.0},
 'protocol': {'subcategory': 'persistent_regional_anomaly_verification',
              'thresholds': {'support_mean_abs_p75': 0.7763,
                             'refute_mean_abs_p50': 0.4078,
                             'support_fraction_above_p75': 0.25,
                             'refute_fraction_above_p75': 0.0,
                             'support_completeness_p10': 1.0}},
 'region_cells': [[18.5, 83.5],
                  [18.5, 83.75],
                  [18.5, 84.0],
                  [18.75, 83.5],
                  [18.75, 83.75],
                  [18.75, 84.0],
                  [19.0, 83.5],
                  [19.0, 83.75],
                  [19.0, 84.0]],
 'years': [2021, 2022, 2023],
 'display_metrics': {'year_2021_mean_abs_anomaly': 1.1589,
                     'year_2021_fraction_cells_above_p75': 0.8889,
                     'year_2021_mean_completeness': 1.0,
                     'year_2022_mean_abs_anomaly': 0.7789,
                     'year_2022_fraction_cells_above_p75': 0.4444,
                     'year_2022_mean_completeness': 1.0,
                     'year_2023_mean_abs_anomaly': 1.1242,
                     'year_2023_fraction_cells_above_p75': 0.7778,
                     'year_2023_mean_completeness': 1.0}}

In [ ]:
print(questions[0]["subcategory"])
print()
print(questions[0]["context"].keys())
print()
print(questions[0]["context"])

persistent_regional_anomaly_verification

dict_keys(['decision', 'metrics', 'protocol', 'region_cells', 'years', 'display_metrics'])

{'decision': 'SUPPORTED', 'metrics': {'min_yearly_mean_abs_anomaly': 0.7789, 'min_fraction_cells_above_p75': 0.4444, 'min_yearly_mean_completeness': 1.0}, 'protocol': {'subcategory': 'persistent_regional_anomaly_verification', 'thresholds': {'support_mean_abs_p75': 0.7763, 'refute_mean_abs_p50': 0.4078, 'support_fraction_above_p75': 0.25, 'refute_fraction_above_p75': 0.0, 'support_completeness_p10': 1.0}}, 'region_cells': [[18.5, 83.5], [18.5, 83.75], [18.5, 84.0], [18.75, 83.5], [18.75, 83.75], [18.75, 84.0], [19.0, 83.5], [19.0, 83.75], [19.0, 84.0]], 'years': [2021, 2022, 2023], 'display_metrics': {'year_2021_mean_abs_anomaly': 1.1589, 'year_2021_fraction_cells_above_p75': 0.8889, 'year_2021_mean_completeness': 1.0, 'year_2022_mean_abs_anomaly': 0.7789, 'year_2022_fraction_cells_above_p75': 0.4444, 'year_2022_mean_completeness': 1.0, 'year_2023_mean_abs_anomaly': 1.1242, 'year_2023_fraction_cells_above_p75': 0.7778, 'year_2023_mean_completeness': 1.0}}

In [ ]:
for q in questions:
    if q["subcategory"]=="reliability_aware_claim_verification":
        import pprint
        pprint.pp(q["context"])
        break

{'decision': 'SUPPORTED',
 'metrics': {'mean_abs_anomaly': 1.0057, 'mean_completeness': 1.0},
 'protocol': {'subcategory': 'reliability_aware_claim_verification',
              'thresholds': {'support_mean_abs_q85': 0.8814,
                             'refute_mean_abs_q50': 0.4275,
                             'support_completeness_p50': 1.0}},
 'region_cells': [[20.75, 91.5],
                  [20.75, 91.75],
                  [20.75, 92.0],
                  [21.0, 91.5],
                  [21.0, 91.75],
                  [21.0, 92.0],
                  [21.25, 91.5],
                  [21.25, 91.75],
                  [21.25, 92.0]],
 'year': 2023,
 'display_metrics': {'mean_abs_anomaly': 1.0057,
                     'cell_01_completeness': 1.0,
                     'cell_02_completeness': 1.0,
                     'cell_03_completeness': 1.0,
                     'cell_04_completeness': 1.0,
                     'cell_05_completeness': 1.0,
                     'cell_06_completeness': 1.0,
                     'cell_07_completeness': 1.0,
                     'cell_08_completeness': 1.0,
                     'cell_09_completeness': 1.0}}

In [ ]:
rows = []

n = min(
    len(m1),
    len(m2),
    len(m3),
    len(decisions),
    len(questions)
)

for i in range(n):

    q = questions[i]

    metrics = q["context"]["metrics"]

    row = {

        "id": q["id"],
        "subcategory": q["subcategory"],

        "GT_Decision": q["answer"],
        "Pred_Decision": decisions[i],

        "protocol": q["context"]["protocol"]

    }

    # Ground truth metrics (variable number)
    gt_names = list(metrics.keys())
    gt_values = list(metrics.values())

    for j, (name, value) in enumerate(zip(gt_names, gt_values), start=1):

        row[f"Metric_Name{j}"] = name
        row[f"GT_Metric{j}"] = float(value)

    # Predicted metrics
    row["Pred_Metric1"] = float(m1[i])
    row["Pred_Metric2"] = float(m2[i])

    # Only assign Metric3 if GT has one
    if len(gt_values) >= 3:
        row["Pred_Metric3"] = float(m3[i])
    else:
        row["Pred_Metric3"] = np.nan

    rows.append(row)

df = pd.DataFrame(rows)

print(df.shape)

df.head()

(239, 16)

,id,subcategory,GT_Decision,Pred_Decision,protocol,Metric_Name1,GT_Metric1,Metric_Name2,GT_Metric2,Metric_Name3,GT_Metric3,Pred_Metric1,Pred_Metric2,Pred_Metric3,Metric_Name4,GT_Metric4
0,HYP-001,persistent_regional_anomaly_verification,C,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,0.7789,min_fraction_cells_above_p75,0.4444,min_yearly_mean_completeness,1.0,0.7789,0.4444,1.0,NaN,NaN
1,HYP-002,persistent_regional_anomaly_verification,A,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,1.6805,min_fraction_cells_above_p75,0.8889,min_yearly_mean_completeness,1.0,1.6805,0.8889,1.0,NaN,NaN
2,HYP-003,persistent_regional_anomaly_verification,B,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,0.9982,min_fraction_cells_above_p75,0.6667,min_yearly_mean_completeness,1.0,0.9982,0.6667,1.0,NaN,NaN
3,HYP-004,persistent_regional_anomaly_verification,C,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,1.1584,min_fraction_cells_above_p75,0.7778,min_yearly_mean_completeness,1.0,1.1584,0.7778,1.0,NaN,NaN
4,HYP-005,persistent_regional_anomaly_verification,C,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,0.8405,min_fraction_cells_above_p75,0.6667,min_yearly_mean_completeness,1.0,0.8405,0.6667,1.0,NaN,NaN

In [ ]:
import sys

sys.path.append("../../src")

from hypothesis_benchmark_generator_v2 import classify_with_thresholds

In [ ]:
print(df[df["subcategory"]=="localized_intensification_verification"].head())

         id                             subcategory GT_Decision Pred_Decision  \
40  HYP-041  localized_intensification_verification           C             A
41  HYP-042  localized_intensification_verification           C             A
42  HYP-043  localized_intensification_verification           C             A
43  HYP-044  localized_intensification_verification           C             A
44  HYP-045  localized_intensification_verification           A             A

                                             protocol  \
40  {'subcategory': 'localized_intensification_ver...
41  {'subcategory': 'localized_intensification_ver...
42  {'subcategory': 'localized_intensification_ver...
43  {'subcategory': 'localized_intensification_ver...
44  {'subcategory': 'localized_intensification_ver...

                   Metric_Name1  GT_Metric1               Metric_Name2  \
40  regional_abs_anomaly_change      0.8476  border_abs_anomaly_change
41  regional_abs_anomaly_change      0.0936  border_abs_anomaly_change
42  regional_abs_anomaly_change      0.2429  border_abs_anomaly_change
43  regional_abs_anomaly_change      1.2485  border_abs_anomaly_change
44  regional_abs_anomaly_change      0.1536  border_abs_anomaly_change

    GT_Metric2               Metric_Name3  GT_Metric3  Pred_Metric1  \
40      0.4088  localized_contrast_change      0.4388        0.8476
41     -0.1657  localized_contrast_change      0.2592        0.0936
42      0.0494  localized_contrast_change      0.1935        0.2429
43      0.8575  localized_contrast_change      0.3910        1.2485
44      0.0014  localized_contrast_change      0.1522        0.1536

    Pred_Metric2  Pred_Metric3              Metric_Name4  GT_Metric4
40        0.4388        1.9395  regional_rainfall_change      1.9395
41        0.2593        0.3405  regional_rainfall_change      0.3405
42        0.1935        0.4704  regional_rainfall_change      0.4704
43        0.3910        2.5151  regional_rainfall_change      2.5151
44        0.1522        0.6319  regional_rainfall_change      0.6319

In [ ]:
q = next(
    q for q in questions
    if q["subcategory"]=="localized_intensification_verification"
)

import pprint
pprint.pp(q["context"]["metrics"])

{'regional_abs_anomaly_change': 0.8476,
 'border_abs_anomaly_change': 0.4088,
 'localized_contrast_change': 0.4388,
 'regional_rainfall_change': 1.9395}

In [ ]:
from collections import defaultdict

metric_names = defaultdict(set)

for q in questions:
    metric_names[q["subcategory"]].update(q["context"]["metrics"].keys())

for k,v in metric_names.items():
    print("\n",k)
    print(sorted(v))

 persistent_regional_anomaly_verification
['min_fraction_cells_above_p75', 'min_yearly_mean_abs_anomaly', 'min_yearly_mean_completeness']

 localized_intensification_verification
['border_abs_anomaly_change', 'localized_contrast_change', 'regional_abs_anomaly_change', 'regional_rainfall_change']

 wet_anomaly_consistency_verification
['fraction_cells_rainfall_increased', 'mean_signed_anomaly_later_year', 'regional_rainfall_change']

 compound_state_transition_verification
['regional_rainfall_change', 'regional_temperature_change']

 spatial_coherence_verification
['active_cell_count', 'component_count', 'largest_component_share', 'largest_component_size']

 reliability_aware_claim_verification
['mean_abs_anomaly', 'mean_completeness']

In [ ]:
ORACLE_METRICS = {

    "persistent_regional_anomaly_verification": [
        "min_yearly_mean_abs_anomaly",
        "min_fraction_cells_above_p75",
        "min_yearly_mean_completeness"
    ],

    "localized_intensification_verification": [
        "regional_abs_anomaly_change",
        "localized_contrast_change",
        "regional_rainfall_change"
    ],

    "wet_anomaly_consistency_verification": [
        "mean_signed_anomaly_later_year",
        "regional_rainfall_change",
        "fraction_cells_rainfall_increased"
    ],

    "compound_state_transition_verification": [
        "regional_rainfall_change",
        "regional_temperature_change"
    ],

    "spatial_coherence_verification": [
        "active_cell_count",
        "largest_component_size",
        "component_count"
    ],

    "reliability_aware_claim_verification": [
        "mean_abs_anomaly",
        "mean_completeness"
    ]

}

In [ ]:
rows = []

n = min(
    len(m1),
    len(m2),
    len(m3),
    len(decisions),
    len(questions)
)

print("Using", n, "responses")

for i in range(n):

    q = questions[i]

    sub = q["subcategory"]

    oracle = ORACLE_METRICS[sub]

    gt = q["context"]["metrics"]

    row = {

        "id": q["id"],
        "subcategory": sub,

        "GT_Decision": q["context"]["decision"],
        "Pred_Decision": decisions[i],

        "protocol": q["context"]["protocol"]

    }

    preds = [
        float(m1[i]),
        float(m2[i]),
        float(m3[i])
    ]

    for j, metric_name in enumerate(oracle):

        row[f"Metric_Name{j+1}"] = metric_name

        row[f"GT_Metric{j+1}"] = gt[metric_name]

        row[f"Pred_Metric{j+1}"] = preds[j]

    rows.append(row)

df = pd.DataFrame(rows)

print(df.shape)

df.head()

Using 239 responses
(239, 14)

,id,subcategory,GT_Decision,Pred_Decision,protocol,Metric_Name1,GT_Metric1,Pred_Metric1,Metric_Name2,GT_Metric2,Pred_Metric2,Metric_Name3,GT_Metric3,Pred_Metric3
0,HYP-001,persistent_regional_anomaly_verification,SUPPORTED,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,0.7789,0.7789,min_fraction_cells_above_p75,0.4444,0.4444,min_yearly_mean_completeness,1.0,1.0
1,HYP-002,persistent_regional_anomaly_verification,SUPPORTED,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,1.6805,1.6805,min_fraction_cells_above_p75,0.8889,0.8889,min_yearly_mean_completeness,1.0,1.0
2,HYP-003,persistent_regional_anomaly_verification,SUPPORTED,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,0.9982,0.9982,min_fraction_cells_above_p75,0.6667,0.6667,min_yearly_mean_completeness,1.0,1.0
3,HYP-004,persistent_regional_anomaly_verification,SUPPORTED,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,1.1584,1.1584,min_fraction_cells_above_p75,0.7778,0.7778,min_yearly_mean_completeness,1.0,1.0
4,HYP-005,persistent_regional_anomaly_verification,SUPPORTED,A,{'subcategory': 'persistent_regional_anomaly_v...,min_yearly_mean_abs_anomaly,0.8405,0.8405,min_fraction_cells_above_p75,0.6667,0.6667,min_yearly_mean_completeness,1.0,1.0

In [ ]:
df[df["subcategory"]=="localized_intensification_verification"].head()

,id,subcategory,GT_Decision,Pred_Decision,protocol,Metric_Name1,GT_Metric1,Pred_Metric1,Metric_Name2,GT_Metric2,Pred_Metric2,Metric_Name3,GT_Metric3,Pred_Metric3
40,HYP-041,localized_intensification_verification,SUPPORTED,A,{'subcategory': 'localized_intensification_ver...,regional_abs_anomaly_change,0.8476,0.8476,localized_contrast_change,0.4388,0.4388,regional_rainfall_change,1.9395,1.9395
41,HYP-042,localized_intensification_verification,SUPPORTED,A,{'subcategory': 'localized_intensification_ver...,regional_abs_anomaly_change,0.0936,0.0936,localized_contrast_change,0.2592,0.2593,regional_rainfall_change,0.3405,0.3405
42,HYP-043,localized_intensification_verification,SUPPORTED,A,{'subcategory': 'localized_intensification_ver...,regional_abs_anomaly_change,0.2429,0.2429,localized_contrast_change,0.1935,0.1935,regional_rainfall_change,0.4704,0.4704
43,HYP-044,localized_intensification_verification,SUPPORTED,A,{'subcategory': 'localized_intensification_ver...,regional_abs_anomaly_change,1.2485,1.2485,localized_contrast_change,0.3910,0.3910,regional_rainfall_change,2.5151,2.5151
44,HYP-045,localized_intensification_verification,SUPPORTED,A,{'subcategory': 'localized_intensification_ver...,regional_abs_anomaly_change,0.1536,0.1536,localized_contrast_change,0.1522,0.1522,regional_rainfall_change,0.6319,0.6319

In [ ]:
recovered = []

for _, row in df.iterrows():

    metrics = {}

    for i in range(1,5):

        name = row.get(f"Metric_Name{i}")

        if pd.isna(name):
            continue

        metrics[name] = row[f"Pred_Metric{i}"] if False else row[f"Pred_Metric{i}"]

    recovered.append(
        classify_with_thresholds(
            metrics,
            row["protocol"]
        )
    )

df["RecoveredDecision"] = recovered

In [ ]:
acc = (
    df["RecoveredDecision"]
    ==
    df["GT_Decision"]
).mean()*100

print(f"Recovered Decision Accuracy = {acc:.2f}%")

Recovered Decision Accuracy = 98.74%

In [ ]:
from sklearn.metrics import mean_absolute_error

for i in range(1,4):

    gt = f"GT_Metric{i}"
    pred = f"Pred_Metric{i}"

    if gt not in df.columns:
        continue

    temp = df[[gt,pred]].dropna()

    mae = mean_absolute_error(
        temp[gt],
        temp[pred]
    )

    exact = (
        (
            temp[gt].round(4)
            ==
            temp[pred].round(4)
        ).mean()*100
    )

    print("="*50)
    print(gt)
    print("Rows :",len(temp))
    print("MAE  :",mae)
    print("Exact:",exact,"%")

==================================================
GT_Metric1
Rows : 239
MAE  : 0.1377912133891214
Exact: 78.24267782426779 %
==================================================
GT_Metric2
Rows : 239
MAE  : 0.06276820083682008
Exact: 89.5397489539749 %
==================================================
GT_Metric3
Rows : 160
MAE  : 0.08125
Exact: 95.0 %

In [ ]:
parsed_ids = set(df["id"])

all_ids = {q["id"] for q in questions}

missing = sorted(all_ids - parsed_ids)

print(missing)

['HYP-240']

In [ ]:
errors = df[df["RecoveredDecision"] != df["GT_Decision"]]

print(errors[[
    "id",
    "subcategory",
    "GT_Decision",
    "RecoveredDecision"
]])

          id                           subcategory GT_Decision  \
185  HYP-186        spatial_coherence_verification     REFUTED
212  HYP-213  reliability_aware_claim_verification   SUPPORTED
225  HYP-226  reliability_aware_claim_verification     REFUTED

    RecoveredDecision
185      INSUFFICIENT
212           REFUTED
225      INSUFFICIENT

In [ ]:
interesting = ["HYP-186","HYP-213","HYP-226"]

for qid in interesting:

    print("="*80)

    row = df[df.id==qid].iloc[0]

    print("ID:",qid)
    print("Category:",row.subcategory)

    print()

    print("GT Decision :",row.GT_Decision)
    print("Recovered   :",row.RecoveredDecision)

    print()

    for i in range(1,4):

        name=f"Metric_Name{i}"

        if name not in row or pd.isna(row[name]):
            continue

        gt=row[f"GT_Metric{i}"]

        pred=row[f"Pred_Metric{i}"]

        print(row[name])

        print("GT  :",gt)

        print("Pred:",pred)

        print()

================================================================================
ID: HYP-186
Category: spatial_coherence_verification

GT Decision : REFUTED
Recovered   : INSUFFICIENT

active_cell_count
GT  : 4.0
Pred: 2.0

largest_component_size
GT  : 1.0
Pred: 2.0

component_count
GT  : 4.0
Pred: 1.0

================================================================================
ID: HYP-213
Category: reliability_aware_claim_verification

GT Decision : SUPPORTED
Recovered   : REFUTED

mean_abs_anomaly
GT  : 1.5182
Pred: 0.3489

mean_completeness
GT  : 1.0
Pred: 1.0

================================================================================
ID: HYP-226
Category: reliability_aware_claim_verification

GT Decision : REFUTED
Recovered   : INSUFFICIENT

mean_abs_anomaly
GT  : 0.2557
Pred: 0.497

mean_completeness
GT  : 1.0
Pred: 1.0

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path

In [ ]:
from pathlib import Path

RESULTS = Path(r"E:\ClimateTwinIndia\experiments\experiment_05_derivation\results")

claude = pd.read_csv(RESULTS / "claude_derivation.csv")
deepseek = pd.read_csv(RESULTS / "deepseek_derivation.csv")
gpt = pd.read_csv(RESULTS / "gpt_derivation.csv")

In [ ]:
from pathlib import Path

PROJECT = Path.cwd()

while PROJECT.name != "ClimateTwinIndia":
    PROJECT = PROJECT.parent

RESULTS = PROJECT / "experiments" / "experiment_05_derivation" / "results"

print("Project:", PROJECT)
print("Results:", RESULTS)
print("Exists:", RESULTS.exists())

Project: e:\ClimateTwinIndia
Results: e:\ClimateTwinIndia\experiments\experiment_05_derivation\results
Exists: True

In [ ]:

from pathlib import Path
import pandas as pd

PROJECT = Path.cwd()

while PROJECT.name != "ClimateTwinIndia":
    PROJECT = PROJECT.parent

RESULTS = PROJECT / "experiments" / "experiment_05_derivation" / "results"

claude = pd.read_csv(RESULTS / "claude_derivation.csv")
deepseek = pd.read_csv(RESULTS / "deepseek_derivation.csv")
gpt = pd.read_csv(RESULTS / "gpt_derivation.csv")

claude_summary = pd.read_csv(RESULTS / "claude_metric_summary.csv")
deepseek_summary = pd.read_csv(RESULTS / "deepseek_metric_summary.csv")
gpt_summary = pd.read_csv(RESULTS / "gpt_metric_summary.csv")

In [5]:
import pandas as pd
import numpy as np

# =====================================
# CHANGE MODEL HERE
# =====================================

MODEL = "deepseek"

df = pd.read_csv(
    rf"E:\ClimateTwinIndia\experiments\experiment_05_derivation\results\{MODEL}_derivation.csv"
)

# =====================================
# Metric correctness
# =====================================

TOL = 1e-4

df["Metric1_Correct"] = (
    np.abs(df["GT_Metric1"] - df["Pred_Metric1"]) <= TOL
)

df["Metric2_Correct"] = (
    np.abs(df["GT_Metric2"] - df["Pred_Metric2"]) <= TOL
)

df["Metric3_Correct"] = (
    df["GT_Metric3"].isna()
    |
    (
        np.abs(df["GT_Metric3"] - df["Pred_Metric3"])
        <= TOL
    )
)

df["All_Metrics_Correct"] = (
    df["Metric1_Correct"]
    &
    df["Metric2_Correct"]
    &
    df["Metric3_Correct"]
)

# =====================================
# Per-category summary
# =====================================

rows = []

for cat, g in df.groupby("subcategory"):

    rows.append({

        "Category": cat,

        "Questions": len(g),

        "Metric Accuracy (%)":
            round(
                100 * g["All_Metrics_Correct"].mean(),
                2
            ),

        "Decision Accuracy (%)":
            round(
                100 * g["Decision_Correct"].mean(),
                2
            ),

        "Metric Errors":
            (~g["All_Metrics_Correct"]).sum(),

        "Decision Errors":
            (~g["Decision_Correct"]).sum(),

        "Absorbed Errors":
            (
                (~g["All_Metrics_Correct"])
                &
                (g["Decision_Correct"])
            ).sum(),

        "Propagated Errors":
            (
                (~g["All_Metrics_Correct"])
                &
                (~g["Decision_Correct"])
            ).sum()

    })

summary = (
    pd.DataFrame(rows)
    .sort_values("Category")
)

print(summary)

summary.to_csv(
    f"{MODEL}_category_summary.csv",
    index=False
)

print("\nSaved:", f"{MODEL}_category_summary.csv")

                                   Category  Questions  Metric Accuracy (%)  \
0    compound_state_transition_verification         40                100.0
1    localized_intensification_verification         40                 92.5
2  persistent_regional_anomaly_verification         40                 92.5
3      reliability_aware_claim_verification         40                100.0
4            spatial_coherence_verification         40                 72.5
5      wet_anomaly_consistency_verification         40                100.0

   Decision Accuracy (%)  Metric Errors  Decision Errors  Absorbed Errors  \
0                  100.0              0                0                0
1                  100.0              3                0                3
2                  100.0              3                0                3
3                  100.0              0                0                0
4                   97.5             11                1               10
5                  100.0              0                0                0

   Propagated Errors
0                  0
1                  0
2                  0
3                  0
4                  1
5                  0

Saved: deepseek_category_summary.csv

In [6]:
prop = df[
    (~df["All_Metrics_Correct"])
    &
    (~df["Decision_Correct"])
]

print("="*80)
print("PROPAGATED FAILURES")
print("="*80)

cols = [
    "id",
    "subcategory",
    "GT_Decision",
    "RecoveredDecision",
    "GT_Metric1","Pred_Metric1",
    "GT_Metric2","Pred_Metric2",
    "GT_Metric3","Pred_Metric3"
]

print(prop[cols])

print("\nTotal propagated:", len(prop))

================================================================================
PROPAGATED FAILURES
================================================================================
          id                     subcategory GT_Decision RecoveredDecision  \
185  HYP-186  spatial_coherence_verification     REFUTED      INSUFFICIENT

     GT_Metric1  Pred_Metric1  GT_Metric2  Pred_Metric2  GT_Metric3  \
185         4.0           2.0         1.0           2.0         4.0

     Pred_Metric3
185           1.0

Total propagated: 1

In [7]:
import pandas as pd
import numpy as np
from pathlib import Path

# ==========================================================
# CHANGE THIS TO YOUR RESULTS DIRECTORY
# ==========================================================

RESULTS = Path(r"E:\ClimateTwinIndia\experiments\experiment_05_derivation\results")

MODELS = [
    "claude",
    "claude_opus",
    "deepseek",
    "gemini",
    "gpt"
]

TOL = 1e-4

rows = []

for model in MODELS:

    file = RESULTS / f"{model}_derivation.csv"

    if not file.exists():
        print(f"Missing: {file}")
        continue

    df = pd.read_csv(file)

    # -----------------------------
    # Metric correctness
    # -----------------------------

    m1 = np.abs(df.GT_Metric1 - df.Pred_Metric1) <= TOL
    m2 = np.abs(df.GT_Metric2 - df.Pred_Metric2) <= TOL

    m3 = (
        df.GT_Metric3.isna()
        |
        (np.abs(df.GT_Metric3 - df.Pred_Metric3) <= TOL)
    )

    metric_correct = m1 & m2 & m3

    decision_correct = df.Decision_Correct

    metric_errors = (~metric_correct).sum()

    absorbed = (
        (~metric_correct)
        &
        (decision_correct)
    ).sum()

    propagated = (
        (~metric_correct)
        &
        (~decision_correct)
    ).sum()

    rows.append({

        "Model": model.replace("_"," ").title(),

        "Questions":
            len(df),

        "Protocol Recovery (%)":
            round(
                100*decision_correct.mean(),
                2
            ),

        "Metric Accuracy (%)":
            round(
                100*metric_correct.mean(),
                2
            ),

        "Metric Errors":
            int(metric_errors),

        "Absorbed":
            int(absorbed),

        "Propagated":
            int(propagated),

        "Absorption Rate (%)":
            round(
                100*absorbed/max(metric_errors,1),
                2
            ),

        "Propagation Rate (%)":
            round(
                100*propagated/max(metric_errors,1),
                2
            )

    })

summary = pd.DataFrame(rows)

summary = summary.sort_values(
    "Protocol Recovery (%)",
    ascending=False
)

print("\n")
print("="*110)
print(summary)
print("="*110)

summary.to_csv(
    RESULTS/"master_isolation_summary.csv",
    index=False
)

print("\nSaved:")
print(RESULTS/"master_isolation_summary.csv")

==============================================================================================================
         Model  Questions  Protocol Recovery (%)  Metric Accuracy (%)  \
0       Claude        240                 100.00                97.92
1  Claude Opus        240                 100.00                98.75
3       Gemini        240                 100.00               100.00
2     Deepseek        240                  99.58                92.92
4          Gpt        240                  42.92                 4.17

   Metric Errors  Absorbed  Propagated  Absorption Rate (%)  \
0              5         5           0               100.00
1              3         3           0               100.00
3              0         0           0                 0.00
2             17        16           1                94.12
4            230        93         137                40.43

   Propagation Rate (%)
0                  0.00
1                  0.00
3                  0.00
2                  5.88
4                 59.57
==============================================================================================================

Saved:
E:\ClimateTwinIndia\experiments\experiment_05_derivation\results\master_isolation_summary.csv

In [8]:
latex = summary.to_latex(
    index=False,
    float_format="%.2f",
    escape=False
)

with open(RESULTS/"master_isolation_summary.tex","w",encoding="utf8") as f:
    f.write(latex)

print(latex)

\begin{tabular}{lrrrrrrrr}
\toprule
Model & Questions & Protocol Recovery (%) & Metric Accuracy (%) & Metric Errors & Absorbed & Propagated & Absorption Rate (%) & Propagation Rate (%) \\
\midrule
Claude & 240 & 100.00 & 97.92 & 5 & 5 & 0 & 100.00 & 0.00 \\
Claude Opus & 240 & 100.00 & 98.75 & 3 & 3 & 0 & 100.00 & 0.00 \\
Gemini & 240 & 100.00 & 100.00 & 0 & 0 & 0 & 0.00 & 0.00 \\
Deepseek & 240 & 99.58 & 92.92 & 17 & 16 & 1 & 94.12 & 5.88 \\
Gpt & 240 & 42.92 & 4.17 & 230 & 93 & 137 & 40.43 & 59.57 \\
\bottomrule
\end{tabular}

In [9]:
from pathlib import Path
import pandas as pd
import numpy as np

RESULTS = Path("results")

MODELS = {
    "Claude": "claude",
    "Claude Opus": "claude_opus",
    "DeepSeek": "deepseek",
    "Gemini": "gemini",
    "GPT": "gpt"
}

out = []

out.append("="*90)
out.append("CLIMATETWINBENCH - MASTER PAPER STATISTICS")
out.append("="*90)
out.append("")

###############################################################
# Helper
###############################################################

def metric_correct(df):

    m1 = np.isclose(df["GT_Metric1"], df["Pred_Metric1"], atol=1e-4)

    m2 = np.isclose(df["GT_Metric2"], df["Pred_Metric2"], atol=1e-4)

    if "GT_Metric3" in df.columns:

        m3 = (
            df["GT_Metric3"].isna()
            |
            np.isclose(
                df["GT_Metric3"],
                df["Pred_Metric3"],
                atol=1e-4
            )
        )

    else:
        m3 = True

    return m1 & m2 & m3


###############################################################
# Overall model summaries
###############################################################

master = []

for nice_name, model in MODELS.items():

    file = RESULTS / f"{model}_derivation.csv"

    if not file.exists():
        continue

    df = pd.read_csv(file)

    metric = metric_correct(df)

    decision = df["Decision_Correct"]

    total = len(df)

    metric_errors = (~metric).sum()

    absorbed = ((~metric) & decision).sum()

    propagated = ((~metric) & (~decision)).sum()

    protocol = decision.mean()*100

    metric_acc = metric.mean()*100

    absorb_rate = (
        absorbed/metric_errors*100
        if metric_errors else 0
    )

    prop_rate = (
        propagated/metric_errors*100
        if metric_errors else 0
    )

    master.append({
        "Model": nice_name,
        "Questions": total,
        "Protocol Recovery": protocol,
        "Metric Accuracy": metric_acc,
        "Metric Errors": metric_errors,
        "Absorbed": absorbed,
        "Propagated": propagated,
        "Absorption Rate": absorb_rate,
        "Propagation Rate": prop_rate
    })

master_df = pd.DataFrame(master)

out.append("OVERALL MODEL PERFORMANCE")
out.append("-"*90)
out.append(master_df.to_string(index=False))
out.append("")
out.append("")

###############################################################
# Per-category summaries
###############################################################

out.append("="*90)
out.append("PER-CATEGORY SUMMARY")
out.append("="*90)
out.append("")

for nice_name, model in MODELS.items():

    file = RESULTS / f"{model}_derivation.csv"

    if not file.exists():
        continue

    df = pd.read_csv(file)

    metric = metric_correct(df)

    df["MetricCorrect"] = metric

    out.append(f"\n{nice_name}")
    out.append("-"*50)

    summary = []

    for cat, g in df.groupby("subcategory"):

        mc = g["MetricCorrect"]

        dc = g["Decision_Correct"]

        metric_errors = (~mc).sum()

        absorbed = ((~mc) & dc).sum()

        propagated = ((~mc) & (~dc)).sum()

        summary.append({

            "Category":cat,

            "Questions":len(g),

            "MetricAcc":round(mc.mean()*100,2),

            "DecisionAcc":round(dc.mean()*100,2),

            "MetricErrors":metric_errors,

            "Absorbed":absorbed,

            "Propagated":propagated

        })

    out.append(
        pd.DataFrame(summary).to_string(index=False)
    )
    out.append("")

###############################################################
# Propagated failures
###############################################################

out.append("="*90)
out.append("PROPAGATED FAILURES")
out.append("="*90)
out.append("")

for nice_name, model in MODELS.items():

    file = RESULTS / f"{model}_derivation.csv"

    if not file.exists():
        continue

    df = pd.read_csv(file)

    metric = metric_correct(df)

    fail = df[(~metric) & (~df["Decision_Correct"])]

    out.append(f"\n{nice_name}")

    if len(fail)==0:

        out.append("None\n")
        continue

    cols=[
        "id",
        "subcategory",
        "GT_Decision",
        "RecoveredDecision",
        "GT_Metric1",
        "Pred_Metric1",
        "GT_Metric2",
        "Pred_Metric2",
        "GT_Metric3",
        "Pred_Metric3"
    ]

    out.append(
        fail[cols].to_string(index=False)
    )
    out.append("")

###############################################################
# Benchmark totals
###############################################################

out.append("="*90)
out.append("BENCHMARK TOTALS")
out.append("="*90)
out.append("")

example = pd.read_csv(
    RESULTS/"claude_derivation.csv"
)

out.append(f"Questions                  : {len(example)}")
out.append(f"Categories                 : {example.subcategory.nunique()}")

out.append(
    f"Persistent                 : {(example.subcategory=='persistent_regional_anomaly_verification').sum()}"
)

out.append(
    f"Localized                  : {(example.subcategory=='localized_intensification_verification').sum()}"
)

out.append(
    f"Wet                        : {(example.subcategory=='wet_anomaly_consistency_verification').sum()}"
)

out.append(
    f"Compound                   : {(example.subcategory=='compound_state_transition_verification').sum()}"
)

out.append(
    f"Spatial                    : {(example.subcategory=='spatial_coherence_verification').sum()}"
)

out.append(
    f"Reliability                : {(example.subcategory=='reliability_aware_claim_verification').sum()}"
)

out.append("")

###############################################################
# Save
###############################################################

outfile = RESULTS/"paper_numbers.txt"

with open(outfile,"w",encoding="utf8") as f:

    f.write("\n".join(out))

print("="*80)
print("Saved")
print(outfile)
print("="*80)

================================================================================
Saved
results\paper_numbers.txt
================================================================================

In [10]:
from pathlib import Path
import pandas as pd
import numpy as np

RESULTS = Path("results")
TABLES = RESULTS / "latex_tables"
TABLES.mkdir(exist_ok=True)

MODELS = {
    "Claude": "claude",
    "Claude Opus": "claude_opus",
    "DeepSeek": "deepseek",
    "Gemini": "gemini",
    "GPT-OSS-120B": "gpt"
}


# ---------------------------------------------------------
# Helper
# ---------------------------------------------------------

def metric_correct(df):

    m1 = np.isclose(df.GT_Metric1, df.Pred_Metric1, atol=1e-4)

    m2 = np.isclose(df.GT_Metric2, df.Pred_Metric2, atol=1e-4)

    m3 = (
        df.GT_Metric3.isna()
        |
        np.isclose(
            df.GT_Metric3,
            df.Pred_Metric3,
            atol=1e-4
        )
    )

    return m1 & m2 & m3


# =========================================================
# TABLE 1
# Overall Isolation Results
# =========================================================

rows = []

for pretty, short in MODELS.items():

    file = RESULTS / f"{short}_derivation.csv"

    if not file.exists():
        continue

    df = pd.read_csv(file)

    metric = metric_correct(df)

    decision = df.Decision_Correct

    metric_errors = (~metric).sum()

    absorbed = ((~metric) & decision).sum()

    propagated = ((~metric) & (~decision)).sum()

    rows.append({

        "Model":pretty,

        "Questions":len(df),

        "Protocol Recovery (%)":
            round(decision.mean()*100,2),

        "Metric Accuracy (%)":
            round(metric.mean()*100,2),

        "Metric Errors":metric_errors,

        "Absorbed":absorbed,

        "Propagated":propagated

    })

table1 = pd.DataFrame(rows)

table1.to_latex(

    TABLES/"table1_isolation.tex",

    index=False,

    float_format="%.2f"

)


# =========================================================
# TABLE 2
# Category Breakdown
# =========================================================

rows=[]

for pretty, short in MODELS.items():

    file = RESULTS / f"{short}_derivation.csv"

    if not file.exists():
        continue

    df=pd.read_csv(file)

    metric=metric_correct(df)

    df["MetricCorrect"]=metric

    for cat,g in df.groupby("subcategory"):

        mc=g.MetricCorrect

        dc=g.Decision_Correct

        rows.append({

            "Model":pretty,

            "Category":cat,

            "Metric Accuracy (%)":
                round(mc.mean()*100,2),

            "Decision Accuracy (%)":
                round(dc.mean()*100,2),

            "N":len(g)

        })

table2=pd.DataFrame(rows)

table2.to_latex(

    TABLES/"table2_category_breakdown.tex",

    index=False,

    float_format="%.2f"

)


# =========================================================
# TABLE 3
# Error Absorption
# =========================================================

rows=[]

for pretty, short in MODELS.items():

    file=RESULTS/f"{short}_derivation.csv"

    if not file.exists():
        continue

    df=pd.read_csv(file)

    metric=metric_correct(df)

    decision=df.Decision_Correct

    metric_errors=(~metric).sum()

    absorbed=((~metric)&decision).sum()

    propagated=((~metric)&(~decision)).sum()

    rows.append({

        "Model":pretty,

        "Metric Errors":metric_errors,

        "Absorbed":absorbed,

        "Propagated":propagated,

        "Absorption Rate (%)":
            round(absorbed/max(metric_errors,1)*100,2),

        "Propagation Rate (%)":
            round(propagated/max(metric_errors,1)*100,2)

    })

table3=pd.DataFrame(rows)

table3.to_latex(

    TABLES/"table3_cascade.tex",

    index=False,

    float_format="%.2f"

)


# =========================================================
# TABLE 4
# Propagated Failures
# =========================================================

rows=[]

for pretty, short in MODELS.items():

    file=RESULTS/f"{short}_derivation.csv"

    if not file.exists():
        continue

    df=pd.read_csv(file)

    metric=metric_correct(df)

    fail=df[(~metric)&(~df.Decision_Correct)]

    for _,r in fail.iterrows():

        rows.append({

            "Model":pretty,

            "Question":r.id,

            "Category":r.subcategory,

            "GT":r.GT_Decision,

            "Predicted":r.RecoveredDecision

        })

table4=pd.DataFrame(rows)

table4.to_latex(

    TABLES/"table4_failures.tex",

    index=False

)


# =========================================================
# TABLE 5
# Benchmark Composition
# =========================================================

example=pd.read_csv(
    RESULTS/"claude_derivation.csv"
)

rows=[]

for cat,g in example.groupby("subcategory"):

    rows.append({

        "Category":cat,

        "Questions":len(g)

    })

table5=pd.DataFrame(rows)

table5.to_latex(

    TABLES/"table5_benchmark.tex",

    index=False

)


print("="*70)
print("Generated:")
print("="*70)

for f in sorted(TABLES.glob("*.tex")):
    print(f.name)

print("="*70)

======================================================================
Generated:
======================================================================
table1_isolation.tex
table2_category_breakdown.tex
table3_cascade.tex
table4_failures.tex
table5_benchmark.tex
======================================================================