In [1]:
import json
print("Imported json")

Imported json

In [3]:
import json

with open("../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

import pprint

pprint.pp(bench["questions"][0]["context"])

{'decision': 'SUPPORTED',
 'metrics': {'min_yearly_mean_abs_anomaly': 0.7789,
             'min_fraction_cells_above_p75': 0.4444,
             'min_yearly_mean_completeness': 1.0},
 'protocol': {'subcategory': 'persistent_regional_anomaly_verification',
              'thresholds': {'support_mean_abs_p75': 0.7763,
                             'refute_mean_abs_p50': 0.4078,
                             'support_fraction_above_p75': 0.25,
                             'refute_fraction_above_p75': 0.0,
                             'support_completeness_p10': 1.0}},
 'region_cells': [[18.5, 83.5],
                  [18.5, 83.75],
                  [18.5, 84.0],
                  [18.75, 83.5],
                  [18.75, 83.75],
                  [18.75, 84.0],
                  [19.0, 83.5],
                  [19.0, 83.75],
                  [19.0, 84.0]],
 'years': [2021, 2022, 2023],
 'display_metrics': {'year_2021_mean_abs_anomaly': 1.1589,
                     'year_2021_fraction_cells_above_p75': 0.8889,
                     'year_2021_mean_completeness': 1.0,
                     'year_2022_mean_abs_anomaly': 0.7789,
                     'year_2022_fraction_cells_above_p75': 0.4444,
                     'year_2022_mean_completeness': 1.0,
                     'year_2023_mean_abs_anomaly': 1.1242,
                     'year_2023_fraction_cells_above_p75': 0.7778,
                     'year_2023_mean_completeness': 1.0}}

In [4]:
{'decision': 'SUPPORTED',
 'metrics': {'min_yearly_mean_abs_anomaly': 0.7789,
             'min_fraction_cells_above_p75': 0.4444,
             'min_yearly_mean_completeness': 1.0},
 'protocol': {'subcategory': 'persistent_regional_anomaly_verification',
              'thresholds': {'support_mean_abs_p75': 0.7763,
                             'refute_mean_abs_p50': 0.4078,
                             'support_fraction_above_p75': 0.25,
                             'refute_fraction_above_p75': 0.0,
                             'support_completeness_p10': 1.0}},
 'region_cells': [[18.5, 83.5],
                  [18.5, 83.75],
                  [18.5, 84.0],
                  [18.75, 83.5],
                  [18.75, 83.75],
                  [18.75, 84.0],
                  [19.0, 83.5],
                  [19.0, 83.75],
                  [19.0, 84.0]],
 'years': [2021, 2022, 2023],
 'display_metrics': {'year_2021_mean_abs_anomaly': 1.1589,
                     'year_2021_fraction_cells_above_p75': 0.8889,
                     'year_2021_mean_completeness': 1.0,
                     'year_2022_mean_abs_anomaly': 0.7789,
                     'year_2022_fraction_cells_above_p75': 0.4444,
                     'year_2022_mean_completeness': 1.0,
                     'year_2023_mean_abs_anomaly': 1.1242,
                     'year_2023_fraction_cells_above_p75': 0.7778,
                     'year_2023_mean_completeness': 1.0}}

{'decision': 'SUPPORTED',
 'metrics': {'min_yearly_mean_abs_anomaly': 0.7789,
  'min_fraction_cells_above_p75': 0.4444,
  'min_yearly_mean_completeness': 1.0},
 'protocol': {'subcategory': 'persistent_regional_anomaly_verification',
  'thresholds': {'support_mean_abs_p75': 0.7763,
   'refute_mean_abs_p50': 0.4078,
   'support_fraction_above_p75': 0.25,
   'refute_fraction_above_p75': 0.0,
   'support_completeness_p10': 1.0}},
 'region_cells': [[18.5, 83.5],
  [18.5, 83.75],
  [18.5, 84.0],
  [18.75, 83.5],
  [18.75, 83.75],
  [18.75, 84.0],
  [19.0, 83.5],
  [19.0, 83.75],
  [19.0, 84.0]],
 'years': [2021, 2022, 2023],
 'display_metrics': {'year_2021_mean_abs_anomaly': 1.1589,
  'year_2021_fraction_cells_above_p75': 0.8889,
  'year_2021_mean_completeness': 1.0,
  'year_2022_mean_abs_anomaly': 0.7789,
  'year_2022_fraction_cells_above_p75': 0.4444,
  'year_2022_mean_completeness': 1.0,
  'year_2023_mean_abs_anomaly': 1.1242,
  'year_2023_fraction_cells_above_p75': 0.7778,
  'year_2023_mean_completeness': 1.0}}

In [5]:
import json
import pandas as pd

with open("../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

rows=[]

for q in bench["questions"]:

    row={
        "id":q["id"],
        "answer":q["answer"],
        "subcategory":q["subcategory"],
        "difficulty":q["difficulty"]
    }

    # automatically add every metric
    row.update(q["context"]["metrics"])

    rows.append(row)

gt=pd.DataFrame(rows)

display(gt.head())

,id,answer,subcategory,difficulty,min_yearly_mean_abs_anomaly,min_fraction_cells_above_p75,min_yearly_mean_completeness,regional_abs_anomaly_change,border_abs_anomaly_change,localized_contrast_change,regional_rainfall_change,mean_signed_anomaly_later_year,fraction_cells_rainfall_increased,regional_temperature_change,active_cell_count,largest_component_size,component_count,largest_component_share,mean_abs_anomaly,mean_completeness
0,HYP-001,C,persistent_regional_anomaly_verification,medium,0.7789,0.4444,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HYP-002,A,persistent_regional_anomaly_verification,medium,1.6805,0.8889,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HYP-003,B,persistent_regional_anomaly_verification,medium,0.9982,0.6667,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HYP-004,C,persistent_regional_anomaly_verification,medium,1.1584,0.7778,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HYP-005,C,persistent_regional_anomaly_verification,medium,0.8405,0.6667,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
metric_cols=[
c for c in gt.columns
if c not in ["id","answer","subcategory","difficulty"]
]

metric_cols

['min_yearly_mean_abs_anomaly',
 'min_fraction_cells_above_p75',
 'min_yearly_mean_completeness',
 'regional_abs_anomaly_change',
 'border_abs_anomaly_change',
 'localized_contrast_change',
 'regional_rainfall_change',
 'mean_signed_anomaly_later_year',
 'fraction_cells_rainfall_increased',
 'regional_temperature_change',
 'active_cell_count',
 'largest_component_size',
 'component_count',
 'largest_component_share',
 'mean_abs_anomaly',
 'mean_completeness']

In [9]:
import os

for root, dirs, files in os.walk(".."):
    for f in files:
        if f.endswith(".csv"):
            print(os.path.join(root, f))

..\data\processed\climate_2024.csv
..\data\processed\climate_states_2019.csv
..\data\processed\climate_states_2020.csv
..\data\processed\climate_states_2021.csv
..\data\processed\climate_states_2022.csv
..\data\processed\climate_states_2023.csv
..\data\processed\climate_states_2024.csv
..\data\processed\climate_states_2025.csv
..\data\processed\hotspots_2025.csv
..\data\processed\risk_report_2025.csv
..\results\analysis_category_accuracy.csv
..\results\analysis_overall_accuracy.csv
..\results\decision_accuracy.csv
..\results\difficulty_accuracy.csv
..\results\intermediate_derivation_prompts.csv
..\results\master_analysis.csv
..\results\operation_accuracy.csv
..\results\overall_results.csv
..\results\v1_v2_transition_summary.csv

In [10]:
import pandas as pd

master = pd.read_csv("../results/master_analysis.csv")

print(master.shape)
display(master.head())
print(master.columns.tolist())

(240, 22)

,id,answer,subcategory,difficulty,ChatGPT_V1,ChatGPT_V2,Claude_V1,Claude_V2,DeepSeek_V1,DeepSeek_V2,...,ChatGPT_V1_correct,ChatGPT_V2_correct,Claude_V1_correct,Claude_V2_correct,DeepSeek_V1_correct,DeepSeek_V2_correct,Gemini_V1_correct,Gemini_V2_correct,operation,Decision
0,HYP-001,C,persistent_regional_anomaly_verification,medium,C,C,C,C,C,C,...,True,True,True,True,True,True,False,True,Minimum Selection,SUPPORTED
1,HYP-002,A,persistent_regional_anomaly_verification,medium,A,A,A,A,A,A,...,True,True,True,True,True,True,False,True,Minimum Selection,REFUTED
2,HYP-003,B,persistent_regional_anomaly_verification,medium,B,B,B,B,B,B,...,True,True,True,True,True,True,False,True,Minimum Selection,INSUFFICIENT
3,HYP-004,C,persistent_regional_anomaly_verification,medium,C,C,C,C,C,C,...,True,True,True,True,True,True,False,True,Minimum Selection,SUPPORTED
4,HYP-005,C,persistent_regional_anomaly_verification,medium,C,C,C,C,C,C,...,True,True,True,True,True,True,False,True,Minimum Selection,SUPPORTED

['id', 'answer', 'subcategory', 'difficulty', 'ChatGPT_V1', 'ChatGPT_V2', 'Claude_V1', 'Claude_V2', 'DeepSeek_V1', 'DeepSeek_V2', 'Gemini_V1', 'Gemini_V2', 'ChatGPT_V1_correct', 'ChatGPT_V2_correct', 'Claude_V1_correct', 'Claude_V2_correct', 'DeepSeek_V1_correct', 'DeepSeek_V2_correct', 'Gemini_V1_correct', 'Gemini_V2_correct', 'operation', 'Decision']

In [11]:
import json
import pandas as pd

with open("../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

questions=bench["questions"]

rows=[]

for q in questions:

    ctx=q["context"]
    metrics=ctx["metrics"]

    row={
        "id":q["id"],
        "answer":q["answer"],
        "subcategory":q["subcategory"],
        "difficulty":q["difficulty"]
    }

    # add every metric automatically
    row.update(metrics)

    rows.append(row)

gt=pd.DataFrame(rows)

print(gt.shape)
display(gt.head())

(240, 20)

,id,answer,subcategory,difficulty,min_yearly_mean_abs_anomaly,min_fraction_cells_above_p75,min_yearly_mean_completeness,regional_abs_anomaly_change,border_abs_anomaly_change,localized_contrast_change,regional_rainfall_change,mean_signed_anomaly_later_year,fraction_cells_rainfall_increased,regional_temperature_change,active_cell_count,largest_component_size,component_count,largest_component_share,mean_abs_anomaly,mean_completeness
0,HYP-001,C,persistent_regional_anomaly_verification,medium,0.7789,0.4444,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HYP-002,A,persistent_regional_anomaly_verification,medium,1.6805,0.8889,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HYP-003,B,persistent_regional_anomaly_verification,medium,0.9982,0.6667,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HYP-004,C,persistent_regional_anomaly_verification,medium,1.1584,0.7778,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HYP-005,C,persistent_regional_anomaly_verification,medium,0.8405,0.6667,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
gt.columns.tolist()

['id',
 'answer',
 'subcategory',
 'difficulty',
 'min_yearly_mean_abs_anomaly',
 'min_fraction_cells_above_p75',
 'min_yearly_mean_completeness',
 'regional_abs_anomaly_change',
 'border_abs_anomaly_change',
 'localized_contrast_change',
 'regional_rainfall_change',
 'mean_signed_anomaly_later_year',
 'fraction_cells_rainfall_increased',
 'regional_temperature_change',
 'active_cell_count',
 'largest_component_size',
 'component_count',
 'largest_component_share',
 'mean_abs_anomaly',
 'mean_completeness']

In [13]:
master=pd.read_csv("../results/master_analysis.csv")

master=master.merge(
    gt,
    on=["id","answer","subcategory","difficulty"],
    how="left"
)

print(master.shape)

(240, 38)

In [14]:
import json
import pandas as pd

with open("../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

rows=[]

for q in bench["questions"]:

    row={
        "id":q["id"],
        "subcategory":q["subcategory"]
    }

    thresholds=q["context"]["protocol"]["thresholds"]

    for k,v in thresholds.items():
        row[k]=v

    rows.append(row)

thresholds=pd.DataFrame(rows)

display(thresholds.head())

,id,subcategory,support_mean_abs_p75,refute_mean_abs_p50,support_fraction_above_p75,refute_fraction_above_p75,support_completeness_p10,support_regional_change_q60,refute_regional_change_q25,support_contrast_change_q75,...,active_cell_threshold_yearly_abs_p80,support_active_count_min,refute_active_count_max,support_largest_component_min,refute_largest_component_max,support_component_count_max,refute_component_count_min,support_mean_abs_q85,refute_mean_abs_q50,support_completeness_p50
0,HYP-001,persistent_regional_anomaly_verification,0.7763,0.4078,0.25,0.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HYP-002,persistent_regional_anomaly_verification,0.7226,0.3832,0.25,0.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HYP-003,persistent_regional_anomaly_verification,0.7440,0.3916,0.25,0.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HYP-004,persistent_regional_anomaly_verification,0.7896,0.4256,0.25,0.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HYP-005,persistent_regional_anomaly_verification,0.7226,0.3832,0.25,0.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
master=master.merge(
    thresholds,
    on=["id","subcategory"],
    how="left"
)

print(master.shape)

(240, 68)

In [16]:
import numpy as np

master["threshold_margin"]=np.nan

# Persistent
mask=master["subcategory"]=="persistent_regional_anomaly_verification"

master.loc[mask,"threshold_margin"]=(
master.loc[mask,"min_yearly_mean_abs_anomaly"]
-
master.loc[mask,"support_mean_abs_p75"]
).abs()

# Localized
mask=master["subcategory"]=="localized_intensification_verification"

master.loc[mask,"threshold_margin"]=(
master.loc[mask,"localized_contrast_change"]
-
master.loc[mask,"support_localized_contrast_change"]
).abs()

# Wet
mask=master["subcategory"]=="wet_anomaly_consistency_verification"

master.loc[mask,"threshold_margin"]=(
master.loc[mask,"fraction_cells_rainfall_increased"]
-
master.loc[mask,"support_fraction_rainfall_increased"]
).abs()

# Compound
mask=master["subcategory"]=="compound_state_transition_verification"

master.loc[mask,"threshold_margin"]=(
master.loc[mask,"regional_temperature_change"]
-
master.loc[mask,"support_temperature_change"]
).abs()

# Spatial
mask=master["subcategory"]=="spatial_coherence_verification"

master.loc[mask,"threshold_margin"]=(
master.loc[mask,"largest_component_share"]
-
master.loc[mask,"support_largest_component_share"]
).abs()

# Reliability
mask=master["subcategory"]=="reliability_aware_claim_verification"

master.loc[mask,"threshold_margin"]=(
master.loc[mask,"mean_abs_anomaly"]
-
master.loc[mask,"support_mean_abs_anomaly"]
).abs()

display(master[["id","subcategory","threshold_margin"]].head())

KeyError: 'support_localized_contrast_change'

In [17]:
for c in thresholds.columns:
    print(c)

id
subcategory
support_mean_abs_p75
refute_mean_abs_p50
support_fraction_above_p75
refute_fraction_above_p75
support_completeness_p10
support_regional_change_q60
refute_regional_change_q25
support_contrast_change_q75
refute_contrast_change_q25
support_rainfall_change_q60
refute_rainfall_change_q25
support_signed_anomaly_p75
refute_signed_anomaly_p25
support_rainfall_change_q75
support_fraction_increase_q75
refute_fraction_increase_q25
support_rainfall_change_q66
refute_rainfall_change_q33
support_temperature_change_q66
refute_temperature_change_q33
active_cell_threshold_yearly_abs_p80
support_active_count_min
refute_active_count_max
support_largest_component_min
refute_largest_component_max
support_component_count_max
refute_component_count_min
support_mean_abs_q85
refute_mean_abs_q50
support_completeness_p50

In [18]:
import json

with open("../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

for q in bench["questions"]:
    if q["subcategory"]=="localized_intensification_verification":
        print(q["context"]["protocol"]["thresholds"])
        break

{'support_regional_change_q60': 0.0858, 'refute_regional_change_q25': -0.1941, 'support_contrast_change_q75': 0.1268, 'refute_contrast_change_q25': -0.1287, 'support_rainfall_change_q60': 0.2062, 'refute_rainfall_change_q25': -0.4409}

In [19]:
import numpy as np

master["threshold_margin"] = np.nan

# ---------------- Persistent ----------------

mask = master["subcategory"]=="persistent_regional_anomaly_verification"

master.loc[mask,"threshold_margin"] = (
    master.loc[mask,"min_yearly_mean_abs_anomaly"]
    -
    master.loc[mask,"support_mean_abs_p75"]
).abs()


# ---------------- Localized ----------------

mask = master["subcategory"]=="localized_intensification_verification"

master.loc[mask,"threshold_margin"] = (
    master.loc[mask,"localized_contrast_change"]
    -
    master.loc[mask,"support_contrast_change_q75"]
).abs()


# ---------------- Wet ----------------

mask = master["subcategory"]=="wet_anomaly_consistency_verification"

master.loc[mask,"threshold_margin"] = (
    master.loc[mask,"fraction_cells_rainfall_increased"]
    -
    master.loc[mask,"support_fraction_increase_q75"]
).abs()


# ---------------- Compound ----------------

mask = master["subcategory"]=="compound_state_transition_verification"

master.loc[mask,"threshold_margin"] = (
    master.loc[mask,"regional_temperature_change"]
    -
    master.loc[mask,"support_temperature_change_q66"]
).abs()


# ---------------- Spatial ----------------

mask = master["subcategory"]=="spatial_coherence_verification"

master.loc[mask,"threshold_margin"] = (
    master.loc[mask,"largest_component_size"]
    -
    master.loc[mask,"support_largest_component_min"]
).abs()


# ---------------- Reliability ----------------

mask = master["subcategory"]=="reliability_aware_claim_verification"

master.loc[mask,"threshold_margin"] = (
    master.loc[mask,"mean_abs_anomaly"]
    -
    master.loc[mask,"support_mean_abs_q85"]
).abs()


display(master[[
    "id",
    "subcategory",
    "threshold_margin"
]].head())

        id                               subcategory  threshold_margin
0  HYP-001  persistent_regional_anomaly_verification            0.0026
1  HYP-002  persistent_regional_anomaly_verification            0.9579
2  HYP-003  persistent_regional_anomaly_verification            0.2542
3  HYP-004  persistent_regional_anomaly_verification            0.3688
4  HYP-005  persistent_regional_anomaly_verification            0.1179

In [20]:
median = master["threshold_margin"].median()

master["ThresholdBin"] = np.where(
    master["threshold_margin"] < median,
    "Near",
    "Far"
)

master["ThresholdBin"].value_counts()

ThresholdBin
Near    120
Far     120
Name: count, dtype: int64

In [21]:
rows=[]

for model in ["ChatGPT","Claude","DeepSeek","Gemini"]:

    col=model+"_V2_correct"

    for grp in ["Near","Far"]:

        tmp=master[master["ThresholdBin"]==grp]

        rows.append({
            "Model":model,
            "Threshold":grp,
            "Accuracy":tmp[col].mean()*100
        })

threshold_results=pd.DataFrame(rows)

display(threshold_results)

      Model Threshold   Accuracy
0   ChatGPT      Near  87.500000
1   ChatGPT       Far  92.500000
2    Claude      Near  98.333333
3    Claude       Far  94.166667
4  DeepSeek      Near  99.166667
5  DeepSeek       Far  98.333333
6    Gemini      Near  40.833333
7    Gemini       Far  50.000000

In [22]:
pivot=threshold_results.pivot(
    index="Model",
    columns="Threshold",
    values="Accuracy"
)

display(pivot)

Threshold        Far       Near
Model
ChatGPT    92.500000  87.500000
Claude     94.166667  98.333333
DeepSeek   98.333333  99.166667
Gemini     50.000000  40.833333

In [23]:
import numpy as np

master["normalized_margin"] = np.nan

# ---------------- Persistent ----------------

mask = master["subcategory"]=="persistent_regional_anomaly_verification"

master.loc[mask,"normalized_margin"] = (
    (
        master.loc[mask,"min_yearly_mean_abs_anomaly"]
        -
        master.loc[mask,"support_mean_abs_p75"]
    ).abs()
) / (
    master.loc[mask,"support_mean_abs_p75"]
    -
    master.loc[mask,"refute_mean_abs_p50"]
).abs()


# ---------------- Localized ----------------

mask = master["subcategory"]=="localized_intensification_verification"

master.loc[mask,"normalized_margin"] = (
    (
        master.loc[mask,"localized_contrast_change"]
        -
        master.loc[mask,"support_contrast_change_q75"]
    ).abs()
) / (
    master.loc[mask,"support_contrast_change_q75"]
    -
    master.loc[mask,"refute_contrast_change_q25"]
).abs()


# ---------------- Wet ----------------

mask = master["subcategory"]=="wet_anomaly_consistency_verification"

master.loc[mask,"normalized_margin"] = (
    (
        master.loc[mask,"fraction_cells_rainfall_increased"]
        -
        master.loc[mask,"support_fraction_increase_q75"]
    ).abs()
) / (
    master.loc[mask,"support_fraction_increase_q75"]
    -
    master.loc[mask,"refute_fraction_increase_q25"]
).abs()


# ---------------- Compound ----------------

mask = master["subcategory"]=="compound_state_transition_verification"

master.loc[mask,"normalized_margin"] = (
    (
        master.loc[mask,"regional_temperature_change"]
        -
        master.loc[mask,"support_temperature_change_q66"]
    ).abs()
) / (
    master.loc[mask,"support_temperature_change_q66"]
    -
    master.loc[mask,"refute_temperature_change_q33"]
).abs()


# ---------------- Spatial ----------------

mask = master["subcategory"]=="spatial_coherence_verification"

master.loc[mask,"normalized_margin"] = (
    (
        master.loc[mask,"largest_component_size"]
        -
        master.loc[mask,"support_largest_component_min"]
    ).abs()
) / (
    master.loc[mask,"support_largest_component_min"]
    -
    master.loc[mask,"refute_largest_component_max"]
).abs()


# ---------------- Reliability ----------------

mask = master["subcategory"]=="reliability_aware_claim_verification"

master.loc[mask,"normalized_margin"] = (
    (
        master.loc[mask,"mean_abs_anomaly"]
        -
        master.loc[mask,"support_mean_abs_q85"]
    ).abs()
) / (
    master.loc[mask,"support_mean_abs_q85"]
    -
    master.loc[mask,"refute_mean_abs_q50"]
).abs()

display(master[["id","normalized_margin"]].head())

        id  normalized_margin
0  HYP-001           0.007056
1  HYP-002           2.822334
2  HYP-003           0.721339
3  HYP-004           1.013187
4  HYP-005           0.347378

In [24]:
from scipy.stats import pointbiserialr

for model in ["ChatGPT","Claude","DeepSeek","Gemini"]:

    r,p = pointbiserialr(
        master[model+"_V2_correct"].astype(int),
        master["normalized_margin"]
    )

    print(model)
    print("Correlation =", round(r,3))
    print("p =", p)
    print()

ChatGPT
Correlation = 0.084
p = 0.19444609109614944

Claude
Correlation = -0.043
p = 0.5071498193598177

DeepSeek
Correlation = -0.002
p = 0.977263599878044

Gemini
Correlation = 0.096
p = 0.13833210946499547

In [25]:
master["MarginQuartile"] = pd.qcut(
    master["normalized_margin"],
    4,
    labels=["Q1","Q2","Q3","Q4"]
)

master["MarginQuartile"].value_counts()

MarginQuartile
Q3    63
Q1    60
Q2    60
Q4    57
Name: count, dtype: int64

In [26]:
rows=[]

for model in ["ChatGPT","Claude","DeepSeek","Gemini"]:

    col=model+"_V2_correct"

    for q in ["Q1","Q2","Q3","Q4"]:

        tmp=master[master.MarginQuartile==q]

        rows.append({

            "Model":model,
            "Quartile":q,
            "Accuracy":tmp[col].mean()*100

        })

margin_df=pd.DataFrame(rows)

display(margin_df)

       Model Quartile    Accuracy
0    ChatGPT       Q1   86.666667
1    ChatGPT       Q2   85.000000
2    ChatGPT       Q3   96.825397
3    ChatGPT       Q4   91.228070
4     Claude       Q1   98.333333
5     Claude       Q2   98.333333
6     Claude       Q3   98.412698
7     Claude       Q4   89.473684
8   DeepSeek       Q1  100.000000
9   DeepSeek       Q2  100.000000
10  DeepSeek       Q3   95.238095
11  DeepSeek       Q4  100.000000
12    Gemini       Q1   23.333333
13    Gemini       Q2   48.333333
14    Gemini       Q3   53.968254
15    Gemini       Q4   56.140351

In [27]:
pivot = margin_df.pivot(
    index="Model",
    columns="Quartile",
    values="Accuracy"
)

display(pivot)

Quartile          Q1          Q2         Q3          Q4
Model
ChatGPT    86.666667   85.000000  96.825397   91.228070
Claude     98.333333   98.333333  98.412698   89.473684
DeepSeek  100.000000  100.000000  95.238095  100.000000
Gemini     23.333333   48.333333  53.968254   56.140351

In [28]:
import re
import pandas as pd

def parse_reasoning(text):

    text=str(text)

    metric1=None
    metric2=None
    metric3=None
    decision=None

    patterns=[
        r"Metric[_ ]?1\s*[:=]\s*([\-0-9.]+)",
        r"Metric[_ ]?2\s*[:=]\s*([\-0-9.]+)",
        r"Metric[_ ]?3\s*[:=]\s*([\-0-9.]+)"
    ]

    for i,p in enumerate(patterns):

        m=re.search(p,text,re.I)

        if m:

            value=float(m.group(1))

            if i==0:
                metric1=value

            elif i==1:
                metric2=value

            else:
                metric3=value

    m=re.search(r"Decision\s*[:=]\s*([ABC])",text,re.I)

    if m:
        decision=m.group(1).upper()

    return metric1,metric2,metric3,decision

In [29]:
import json
import pandas as pd

with open("../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

rows=[]

for q in bench["questions"][:40]:   # Persistent category only

    m=q["context"]["metrics"]

    rows.append({

        "id":q["id"],
        "GT_Metric1":m["min_yearly_mean_abs_anomaly"],
        "GT_Metric2":m["min_fraction_cells_above_p75"],
        "GT_Metric3":m["min_yearly_mean_completeness"],
        "GT_Decision":q["answer"]

    })

gt=pd.DataFrame(rows)

display(gt.head())

        id  GT_Metric1  GT_Metric2  GT_Metric3 GT_Decision
0  HYP-001      0.7789      0.4444         1.0           C
1  HYP-002      1.6805      0.8889         1.0           A
2  HYP-003      0.9982      0.6667         1.0           B
3  HYP-004      1.1584      0.7778         1.0           C
4  HYP-005      0.8405      0.6667         1.0           C

In [31]:
import re

with open("../experiments/experiment_05_derivation\\raw_outputs\\deepseek_derivation.txt","r",encoding="utf8") as f:
    txt=f.read()

pattern=r"Metric_1 = ([\-0-9\.]+).*?Metric_2 = ([\-0-9\.]+).*?Metric_3 = ([\-0-9\.]+).*?Decision = ([ABC])"

matches=re.findall(pattern,txt,re.S)

print("Found:",len(matches))

pred=[]

for i,m in enumerate(matches[:40]):

    pred.append({

        "id":f"HYP-{i+1:03d}",
        "Pred_Metric1":float(m[0]),
        "Pred_Metric2":float(m[1]),
        "Pred_Metric3":float(m[2]),
        "Pred_Decision":m[3]

    })

pred=pd.DataFrame(pred)

display(pred.head())

Found: 239

        id  Pred_Metric1  Pred_Metric2  Pred_Metric3 Pred_Decision
0  HYP-001        0.7789        0.4444           1.0             A
1  HYP-002        1.6805        0.8889           1.0             A
2  HYP-003        0.9982        0.6667           1.0             A
3  HYP-004        1.1584        0.7778           1.0             A
4  HYP-005        0.8405        0.6667           1.0             A

In [32]:
df=gt.merge(pred,on="id")

display(df.head())

,id,GT_Metric1,GT_Metric2,GT_Metric3,GT_Decision,Pred_Metric1,Pred_Metric2,Pred_Metric3,Pred_Decision
0,HYP-001,0.7789,0.4444,1.0,C,0.7789,0.4444,1.0,A
1,HYP-002,1.6805,0.8889,1.0,A,1.6805,0.8889,1.0,A
2,HYP-003,0.9982,0.6667,1.0,B,0.9982,0.6667,1.0,A
3,HYP-004,1.1584,0.7778,1.0,C,1.1584,0.7778,1.0,A
4,HYP-005,0.8405,0.6667,1.0,C,0.8405,0.6667,1.0,A

In [33]:
tol=1e-3

df["Metric1_Correct"]=(abs(df.GT_Metric1-df.Pred_Metric1)<tol)

df["Metric2_Correct"]=(abs(df.GT_Metric2-df.Pred_Metric2)<tol)

df["Metric3_Correct"]=(abs(df.GT_Metric3-df.Pred_Metric3)<tol)

df["Decision_Correct"]=(df.GT_Decision==df.Pred_Decision)

print("Metric1:",
      df.Metric1_Correct.mean()*100)

print("Metric2:",
      df.Metric2_Correct.mean()*100)

print("Metric3:",
      df.Metric3_Correct.mean()*100)

print("Decision:",
      df.Decision_Correct.mean()*100)

Metric1: 100.0
Metric2: 100.0
Metric3: 100.0
Decision: 40.0

In [34]:
df["AllMetricsCorrect"]=(
    df["Metric1_Correct"] &
    df["Metric2_Correct"] &
    df["Metric3_Correct"]
)

print(df["AllMetricsCorrect"].mean()*100)

100.0

In [36]:
print(df["AllMetricsCorrect"].value_counts())
print(df["Decision_Correct"].value_counts())

table = pd.crosstab(
    df["AllMetricsCorrect"],
    df["Decision_Correct"]
)

print(table)

AllMetricsCorrect
True    40
Name: count, dtype: int64
Decision_Correct
False    24
True     16
Name: count, dtype: int64
Decision_Correct   False  True
AllMetricsCorrect
True                  24     16

In [37]:
table = pd.crosstab(
    df["AllMetricsCorrect"],
    df["Decision_Correct"]
)

table = table.rename(
    index={
        True:"Metrics Correct",
        False:"Metrics Wrong"
    },
    columns={
        True:"Decision Correct",
        False:"Decision Wrong"
    }
)

display(table)

Decision_Correct   Decision Wrong  Decision Correct
AllMetricsCorrect
Metrics Correct                24                16

In [38]:
print(df["AllMetricsCorrect"].value_counts())
print(df["Decision_Correct"].value_counts())

AllMetricsCorrect
True    40
Name: count, dtype: int64
Decision_Correct
False    24
True     16
Name: count, dtype: int64

In [39]:
summary = pd.DataFrame({

    "Stage":[
        "Metric 1",
        "Metric 2",
        "Metric 3",
        "All Metrics",
        "Final Decision"
    ],

    "Accuracy":[
        df["Metric1_Correct"].mean()*100,
        df["Metric2_Correct"].mean()*100,
        df["Metric3_Correct"].mean()*100,
        df["AllMetricsCorrect"].mean()*100,
        df["Decision_Correct"].mean()*100
    ]

})

display(summary)

            Stage  Accuracy
0        Metric 1     100.0
1        Metric 2     100.0
2        Metric 3     100.0
3     All Metrics     100.0
4  Final Decision      40.0

In [40]:
fail = df[df["Decision_Correct"] == False]

display(

fail[[
"id",
"GT_Decision",
"Pred_Decision",
"GT_Metric1",
"Pred_Metric1",
"GT_Metric2",
"Pred_Metric2",
"GT_Metric3",
"Pred_Metric3"
]]

)

,id,GT_Decision,Pred_Decision,GT_Metric1,Pred_Metric1,GT_Metric2,Pred_Metric2,GT_Metric3,Pred_Metric3
0,HYP-001,C,A,0.7789,0.7789,0.4444,0.4444,1.0,1.0
2,HYP-003,B,A,0.9982,0.9982,0.6667,0.6667,1.0,1.0
3,HYP-004,C,A,1.1584,1.1584,0.7778,0.7778,1.0,1.0
4,HYP-005,C,A,0.8405,0.8405,0.6667,0.6667,1.0,1.0
5,HYP-006,C,A,1.0254,1.0254,0.5556,0.5556,1.0,1.0
7,HYP-008,C,A,0.9184,0.9184,0.5556,0.5556,1.0,1.0
8,HYP-009,B,A,1.0246,1.0246,0.5556,0.5556,1.0,1.0
11,HYP-012,C,A,0.8655,0.8655,0.4444,0.4444,1.0,1.0
13,HYP-014,C,B,0.1953,0.1953,0.0000,0.0000,1.0,1.0
15,HYP-016,A,B,0.3525,0.3525,0.1111,0.1111,1.0,1.0
19,HYP-020,A,B,0.1712,0.1712,0.0000,0.0000,1.0,1.0
21,HYP-022,A,B,0.1321,0.1321,0.0000,0.0000,1.0,1.0
22,HYP-023,A,B,0.1695,0.1695,0.0000,0.0000,1.0,1.0
25,HYP-026,A,B,0.1962,0.1962,0.0000,0.0000,1.0,1.0
26,HYP-027,A,C,0.7209,0.7209,0.4444,0.4444,1.0,1.0
27,HYP-028,B,C,0.5149,0.5149,0.3333,0.3333,1.0,1.0
28,HYP-029,A,C,0.5112,0.5112,0.1111,0.1111,1.0,1.0
29,HYP-030,B,C,0.4902,0.4902,0.1111,0.1111,1.0,1.0
30,HYP-031,A,C,0.4137,0.4137,0.1111,0.1111,1.0,1.0
32,HYP-033,A,C,0.3983,0.3983,0.1111,0.1111,1.0,1.0
34,HYP-035,A,C,0.3877,0.3877,0.1111,0.1111,1.0,1.0
35,HYP-036,B,C,0.8806,0.8806,0.2222,0.2222,1.0,1.0
37,HYP-038,A,C,0.5642,0.5642,0.1111,0.1111,1.0,1.0
38,HYP-039,B,C,0.4631,0.4631,0.1111,0.1111,1.0,1.0

In [41]:
print(fail["Pred_Decision"].value_counts())

Pred_Decision
C    10
A     8
B     6
Name: count, dtype: int64

In [42]:
df = (
    gt
    .merge(pred, on="id")
    .merge(thresholds, on="id")
)

display(df.head())

,id,GT_Metric1,GT_Metric2,GT_Metric3,GT_Decision,Pred_Metric1,Pred_Metric2,Pred_Metric3,Pred_Decision,subcategory,...,active_cell_threshold_yearly_abs_p80,support_active_count_min,refute_active_count_max,support_largest_component_min,refute_largest_component_max,support_component_count_max,refute_component_count_min,support_mean_abs_q85,refute_mean_abs_q50,support_completeness_p50
0,HYP-001,0.7789,0.4444,1.0,C,0.7789,0.4444,1.0,A,persistent_regional_anomaly_verification,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HYP-002,1.6805,0.8889,1.0,A,1.6805,0.8889,1.0,A,persistent_regional_anomaly_verification,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HYP-003,0.9982,0.6667,1.0,B,0.9982,0.6667,1.0,A,persistent_regional_anomaly_verification,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HYP-004,1.1584,0.7778,1.0,C,1.1584,0.7778,1.0,A,persistent_regional_anomaly_verification,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HYP-005,0.8405,0.6667,1.0,C,0.8405,0.6667,1.0,A,persistent_regional_anomaly_verification,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
def recover_persistent(row):

    # SUPPORT
    if (
        row["Pred_Metric1"] >= row["support_mean_abs_p75"]
        and
        row["Pred_Metric2"] >= row["support_fraction_above_p75"]
        and
        row["Pred_Metric3"] >= row["support_completeness_p10"]
    ):
        return "C"

    # REFUTE
    elif (
        row["Pred_Metric1"] <= row["refute_mean_abs_p50"]
        or
        row["Pred_Metric2"] <= row["refute_fraction_above_p75"]
        or
        row["Pred_Metric3"] < row["support_completeness_p10"]
    ):
        return "A"

    # OTHERWISE

    return "B"


df["RecoveredDecision"] = df.apply(
    recover_persistent,
    axis=1
)

In [44]:
df["RecoveredCorrect"] = (
    df["RecoveredDecision"] ==
    df["GT_Decision"]
)

print(
    "Recovered Accuracy:",
    df["RecoveredCorrect"].mean()*100
)

Recovered Accuracy: 37.5

In [45]:
display(

df[
~df["RecoveredCorrect"]
][[
"id",
"GT_Decision",
"RecoveredDecision",
"Pred_Metric1",
"Pred_Metric2",
"Pred_Metric3"
]]

)

,id,GT_Decision,RecoveredDecision,Pred_Metric1,Pred_Metric2,Pred_Metric3
1,HYP-002,A,C,1.6805,0.8889,1.0
2,HYP-003,B,C,0.9982,0.6667,1.0
6,HYP-007,A,C,0.7502,0.5556,1.0
8,HYP-009,B,C,1.0246,0.5556,1.0
9,HYP-010,A,C,0.9352,0.5556,1.0
10,HYP-011,A,C,1.0972,0.4444,1.0
12,HYP-013,A,C,0.7658,0.7778,1.0
13,HYP-014,C,A,0.1953,0.0000,1.0
14,HYP-015,B,A,0.3021,0.0000,1.0
16,HYP-017,B,A,0.2328,0.0000,1.0
17,HYP-018,B,A,0.3349,0.0000,1.0
18,HYP-019,B,A,0.1776,0.0000,1.0
20,HYP-021,B,A,0.1445,0.0000,1.0
23,HYP-024,B,A,0.2083,0.0000,1.0
24,HYP-025,B,A,0.3636,0.1111,1.0
26,HYP-027,A,B,0.7209,0.4444,1.0
28,HYP-029,A,B,0.5112,0.1111,1.0
30,HYP-031,A,B,0.4137,0.1111,1.0
31,HYP-032,C,B,0.4958,0.2222,1.0
32,HYP-033,A,B,0.3983,0.1111,1.0
33,HYP-034,C,B,0.4591,0.2222,1.0
34,HYP-035,A,B,0.3877,0.1111,1.0
36,HYP-037,C,B,0.4648,0.3333,1.0
37,HYP-038,A,B,0.5642,0.1111,1.0
39,HYP-040,C,B,0.4907,0.1111,1.0

In [46]:
pd.crosstab(

    df["GT_Decision"],
    df["RecoveredDecision"],

    rownames=["Ground Truth"],
    colnames=["Recovered"]

)

Recovered     A  B  C
Ground Truth
A             5  6  5
B             7  4  2
C             1  4  6

In [47]:
import os

for root, dirs, files in os.walk(".."):
    for f in files:
        if f.endswith(".py"):
            print(os.path.join(root,f))

..\repository_audit.py
..\src\alerts.py
..\src\benchmark_generator.py
..\src\climate_analysis.py
..\src\climate_database.py
..\src\climate_state.py
..\src\climatology.py
..\src\coordinates.py
..\src\database_builder.py
..\src\domain_reasoning_v2.py
..\src\export_public_benchmark.py
..\src\forecasting.py
..\src\hypothesis_benchmark_generator.py
..\src\hypothesis_benchmark_generator_v2.py
..\src\ingest.py
..\src\loaders.py
..\src\preprocess.py
..\src\region.py
..\src\risk_dashboard.py
..\src\risk_engine.py
..\src\state_engine.py
..\src\trust.py
..\src\utils.py

In [48]:
from pathlib import Path

file = Path("../src/hypothesis_benchmark_generator_v2.py")

with open(file,"r",encoding="utf8") as f:
    lines=f.readlines()

keywords=[
    "answer",
    "decision",
    "SUPPORTED",
    "REFUTED",
    "INSUFFICIENT",
    '"A"',
    '"B"',
    '"C"',
]

for i,line in enumerate(lines):

    if any(k in line for k in keywords):

        print(f"{i+1:4d}: {line.rstrip()}")

   6: state data. Every answer is computed from the ClimateTwinIndia processed
 109:         raise ValueError("Need at least three unique answer options")
 315:         return "SUPPORTED"
 317:         return "REFUTED"
 320:     return "INSUFFICIENT"
 374: def decision_options(decision: str, reason: str, distractor_reasons: dict, seed: int):
 375:     correct = f"{decision} - {reason}"
 376:     labels = ["SUPPORTED", "REFUTED", "INSUFFICIENT"]
 379:         if label == decision:
 385: def difficulty_for(sub: str, decision: str) -> str:
 388:     if decision == "INSUFFICIENT":
 481:     decision,
 486:     opts, ans = decision_options(decision, reason, distractor_reasons, stable_seed(qid, decision))
 504:             "difficulty": difficulty_for(subcategory, decision),
 507:             "answer": ans,
 508:             "explanation": f"Decision={decision}. {reason}. Evidence: "
 511:                 "decision": decision,
 522:     by_decision = defaultdict(list)
 524:         by_decision[c["decision"]].append(c)
 526:     for items in by_decision.values():
 530:     for label in ["SUPPORTED", "REFUTED", "INSUFFICIENT"]:
 531:         selected.extend(by_decision[label][:target_each])
 533:     for label in ["SUPPORTED", "REFUTED", "INSUFFICIENT"]:
 534:         leftovers.extend(by_decision[label][target_each:])
 576:             decision = classify_with_thresholds(metrics, protocol)
 577:             if decision == "AMBIGUOUS":
 596:                 "SUPPORTED if the minimum regional mean |anomaly_score| is at least the printed "
 600:                 "REFUTED if the minimum regional mean |anomaly_score| is at or below refute_mean_abs_p50, "
 603:                 "INSUFFICIENT otherwise."
 606:                 "SUPPORTED": "all persistence, regional coverage, and reliability criteria pass",
 607:                 "REFUTED": "at least one decisive refutation criterion is triggered",
 608:                 "INSUFFICIENT": "the evidence falls between support and refutation thresholds",
 617:                     "decision": decision,
 618:                     "reason": reasons[decision],
 660:             decision = classify_with_thresholds(metrics, protocol)
 661:             if decision == "AMBIGUOUS":
 680:                 "SUPPORTED if regional_abs_anomaly_change is at least its candidate Q60 threshold, "
 683:                 "REFUTED if any corresponding metric is at or below its candidate Q25 refutation threshold. "
 684:                 "INSUFFICIENT otherwise."
 687:                 "SUPPORTED": "regional anomaly, local contrast, and rainfall-change criteria all pass",
 688:                 "REFUTED": "one or more intensification criteria fall at or below a Q25 refutation threshold",
 689:                 "INSUFFICIENT": "the signal is mixed between Q25 refutation and support thresholds",
 698:                     "decision": decision,
 699:                     "reason": reasons[decision],
 738:             decision = classify_with_thresholds(metrics, protocol)
 739:             if decision == "AMBIGUOUS":
 760:                 "SUPPORTED if later-year mean signed anomaly is at least the yearly P75 signed-anomaly "
 763:                 "REFUTED if the signed anomaly is at or below the yearly P25 threshold, or if a high "
 765:                 "below its Q25 refutation threshold. INSUFFICIENT otherwise."
 768:                 "SUPPORTED": "positive-anomaly, rainfall-change, and cell-fraction evidence all pass",
 769:                 "REFUTED": "the anomaly signal or rainfall-consistency evidence triggers refutation",
 770:                 "INSUFFICIENT": "the anomaly and rainfall evidence are not decisive under the printed thresholds",
 779:                     "decision": decision,
 780:                     "reason": reasons[decision],
 828:             decision = classify_with_thresholds(metrics, protocol)
 829:             if decision == "AMBIGUOUS":
 848:                 "SUPPORTED if both changes are at least their candidate Q66 support thresholds. "
 849:                 "REFUTED if either change is at or below its candidate Q33 refutation threshold. "
 850:                 "INSUFFICIENT otherwise."
 853:                 "SUPPORTED": "both rainfall and temperature changes exceed their support thresholds",
 854:                 "REFUTED": "at least one variable falls at or below its refutation threshold",
 855:                 "INSUFFICIENT": "the two-variable transition is neither jointly strong nor decisively refuted",
 864:                     "decision": decision,
 865:                     "reason": reasons[decision],
 919:         decision = classify_with_thresholds(metrics, protocol)
 920:         if decision == "AMBIGUOUS":
 942:             "SUPPORTED if active_cell_count and largest_component_size pass their printed minimum "
 944:             "REFUTED if active_cell_count or largest_component_size is at or below its printed "
 946:             "INSUFFICIENT otherwise."
 949:             "SUPPORTED": "the active cells are numerous enough and concentrated into few connected components",
 950:             "REFUTED": "the active-cell count, largest component size, or fragmentation count triggers refutation",
 951:             "INSUFFICIENT": "the active-cell pattern is between coherent and fragmented thresholds",
 960:                 "decision": decision,
 961:                 "reason": reasons[decision],
 995:             decision = classify_with_thresholds(metrics, protocol)
 996:             if decision == "AMBIGUOUS":
1015:                 "SUPPORTED if mean_abs_anomaly is at least the candidate Q85 regional mean-|anomaly| "
1017:                 "REFUTED if mean_abs_anomaly is at or below the candidate Q50 threshold. "
1018:                 "INSUFFICIENT otherwise."
1021:                 "SUPPORTED": "both anomaly magnitude and completeness pass their support thresholds",
1022:                 "REFUTED": "regional anomaly magnitude is at or below the refutation threshold",
1023:                 "INSUFFICIENT": "the anomaly magnitude is not strong enough for support but not low enough for refutation",
1032:                     "decision": decision,
1033:                     "reason": reasons[decision],
1055:         if sorted(option_labels) != ["INSUFFICIENT", "REFUTED", "SUPPORTED"]:
1057:         if q["answer"] not in q["options"]:
1058:             violations.append((q["id"], "answer letter missing from options"))
1059:         correct_text = q["options"][q["answer"]]
1060:         if not correct_text.startswith(q["context"]["decision"]):
1061:             violations.append((q["id"], "answer text does not match stored decision"))
1063:         if recomputed != q["context"]["decision"]:
1064:             violations.append((q["id"], f"recomputed {recomputed} != stored {q['context']['decision']}"))
1148:             "candidate_decisions": dict(Counter(c["decision"] for c in candidates)),
1161:                     decision=item["decision"],
1171:     by_answer = Counter(q["answer"] for q in questions)
1172:     by_decision = Counter(q["context"]["decision"] for q in questions)
1181:             "answer letter present",
1182:             "stored answer matches recomputed protocol decision",
1184:             "decision protocol and thresholds printed",
1200:             "STRICT: Every answer is derivable programmatically from dataset values alone. "
1221:             "answer_distribution": dict(by_answer),
1222:             "decision_distribution": dict(by_decision),
1248:     for key, n in by_decision.items():
1251:     for key, n in sorted(by_answer.items()):

In [49]:
from pathlib import Path

file = Path("../src/hypothesis_benchmark_generator_v2.py")

with open(file, encoding="utf8") as f:
    lines = f.readlines()

start = 250
end = 340

for i in range(start, end):
    print(f"{i+1:4d}: {lines[i].rstrip()}")

 251:             and metrics["min_yearly_mean_completeness"] >= t["support_completeness_p10"]
 252:         )
 253:         refute = (
 254:             metrics["min_yearly_mean_abs_anomaly"] <= t["refute_mean_abs_p50"]
 255:             or metrics["min_fraction_cells_above_p75"] <= t["refute_fraction_above_p75"]
 256:             or metrics["min_yearly_mean_completeness"] < t["support_completeness_p10"]
 257:         )
 258:     elif sub == "localized_intensification_verification":
 259:         support = (
 260:             metrics["regional_abs_anomaly_change"] >= t["support_regional_change_q60"]
 261:             and metrics["localized_contrast_change"] >= t["support_contrast_change_q75"]
 262:             and metrics["regional_rainfall_change"] >= t["support_rainfall_change_q60"]
 263:         )
 264:         refute = (
 265:             metrics["regional_abs_anomaly_change"] <= t["refute_regional_change_q25"]
 266:             or metrics["localized_contrast_change"] <= t["refute_contrast_change_q25"]
 267:             or metrics["regional_rainfall_change"] <= t["refute_rainfall_change_q25"]
 268:         )
 269:     elif sub == "wet_anomaly_consistency_verification":
 270:         support = (
 271:             metrics["mean_signed_anomaly_later_year"] >= t["support_signed_anomaly_p75"]
 272:             and metrics["regional_rainfall_change"] >= t["support_rainfall_change_q75"]
 273:             and metrics["fraction_cells_rainfall_increased"] >= t["support_fraction_increase_q75"]
 274:         )
 275:         refute = (
 276:             metrics["mean_signed_anomaly_later_year"] <= t["refute_signed_anomaly_p25"]
 277:             or (
 278:                 metrics["mean_signed_anomaly_later_year"] >= t["support_signed_anomaly_p75"]
 279:                 and (
 280:                     metrics["regional_rainfall_change"] <= t["refute_rainfall_change_q25"]
 281:                     or metrics["fraction_cells_rainfall_increased"] <= t["refute_fraction_increase_q25"]
 282:                 )
 283:             )
 284:         )
 285:     elif sub == "compound_state_transition_verification":
 286:         support = (
 287:             metrics["regional_rainfall_change"] >= t["support_rainfall_change_q66"]
 288:             and metrics["regional_temperature_change"] >= t["support_temperature_change_q66"]
 289:         )
 290:         refute = (
 291:             metrics["regional_rainfall_change"] <= t["refute_rainfall_change_q33"]
 292:             or metrics["regional_temperature_change"] <= t["refute_temperature_change_q33"]
 293:         )
 294:     elif sub == "spatial_coherence_verification":
 295:         support = (
 296:             metrics["active_cell_count"] >= t["support_active_count_min"]
 297:             and metrics["largest_component_size"] >= t["support_largest_component_min"]
 298:             and metrics["component_count"] <= t["support_component_count_max"]
 299:         )
 300:         refute = (
 301:             metrics["active_cell_count"] <= t["refute_active_count_max"]
 302:             or metrics["largest_component_size"] <= t["refute_largest_component_max"]
 303:             or metrics["component_count"] >= t["refute_component_count_min"]
 304:         )
 305:     elif sub == "reliability_aware_claim_verification":
 306:         support = (
 307:             metrics["mean_abs_anomaly"] >= t["support_mean_abs_q85"]
 308:             and metrics["mean_completeness"] >= t["support_completeness_p50"]
 309:         )
 310:         refute = metrics["mean_abs_anomaly"] <= t["refute_mean_abs_q50"]
 311:     else:
 312:         raise ValueError(f"Unknown subcategory: {sub}")
 313:
 314:     if support and not refute:
 315:         return "SUPPORTED"
 316:     if refute and not support:
 317:         return "REFUTED"
 318:     if support and refute:
 319:         return "AMBIGUOUS"
 320:     return "INSUFFICIENT"
 321:
 322:
 323: def has_boundary_tie(metrics: dict, protocol: dict) -> bool:
 324:     """Reject examples whose decisive non-degenerate metrics land exactly on a threshold."""
 325:     sub = protocol["subcategory"]
 326:     t = protocol["thresholds"]
 327:     pairs = {
 328:         "persistent_regional_anomaly_verification": [
 329:             ("min_yearly_mean_abs_anomaly", "support_mean_abs_p75"),
 330:             ("min_yearly_mean_abs_anomaly", "refute_mean_abs_p50"),
 331:             ("min_fraction_cells_above_p75", "support_fraction_above_p75"),
 332:         ],
 333:         "localized_intensification_verification": [
 334:             ("regional_abs_anomaly_change", "support_regional_change_q60"),
 335:             ("regional_abs_anomaly_change", "refute_regional_change_q25"),
 336:             ("localized_contrast_change", "support_contrast_change_q75"),
 337:             ("localized_contrast_change", "refute_contrast_change_q25"),
 338:             ("regional_rainfall_change", "support_rainfall_change_q60"),
 339:             ("regional_rainfall_change", "refute_rainfall_change_q25"),
 340:         ],

In [50]:
from pathlib import Path

file = Path("../src/hypothesis_benchmark_generator_v2.py")

with open(file, encoding="utf8") as f:
    lines = f.readlines()

for i in range(260,380):
    print(f"{i+1:4d}: {lines[i].rstrip()}")

 261:             and metrics["localized_contrast_change"] >= t["support_contrast_change_q75"]
 262:             and metrics["regional_rainfall_change"] >= t["support_rainfall_change_q60"]
 263:         )
 264:         refute = (
 265:             metrics["regional_abs_anomaly_change"] <= t["refute_regional_change_q25"]
 266:             or metrics["localized_contrast_change"] <= t["refute_contrast_change_q25"]
 267:             or metrics["regional_rainfall_change"] <= t["refute_rainfall_change_q25"]
 268:         )
 269:     elif sub == "wet_anomaly_consistency_verification":
 270:         support = (
 271:             metrics["mean_signed_anomaly_later_year"] >= t["support_signed_anomaly_p75"]
 272:             and metrics["regional_rainfall_change"] >= t["support_rainfall_change_q75"]
 273:             and metrics["fraction_cells_rainfall_increased"] >= t["support_fraction_increase_q75"]
 274:         )
 275:         refute = (
 276:             metrics["mean_signed_anomaly_later_year"] <= t["refute_signed_anomaly_p25"]
 277:             or (
 278:                 metrics["mean_signed_anomaly_later_year"] >= t["support_signed_anomaly_p75"]
 279:                 and (
 280:                     metrics["regional_rainfall_change"] <= t["refute_rainfall_change_q25"]
 281:                     or metrics["fraction_cells_rainfall_increased"] <= t["refute_fraction_increase_q25"]
 282:                 )
 283:             )
 284:         )
 285:     elif sub == "compound_state_transition_verification":
 286:         support = (
 287:             metrics["regional_rainfall_change"] >= t["support_rainfall_change_q66"]
 288:             and metrics["regional_temperature_change"] >= t["support_temperature_change_q66"]
 289:         )
 290:         refute = (
 291:             metrics["regional_rainfall_change"] <= t["refute_rainfall_change_q33"]
 292:             or metrics["regional_temperature_change"] <= t["refute_temperature_change_q33"]
 293:         )
 294:     elif sub == "spatial_coherence_verification":
 295:         support = (
 296:             metrics["active_cell_count"] >= t["support_active_count_min"]
 297:             and metrics["largest_component_size"] >= t["support_largest_component_min"]
 298:             and metrics["component_count"] <= t["support_component_count_max"]
 299:         )
 300:         refute = (
 301:             metrics["active_cell_count"] <= t["refute_active_count_max"]
 302:             or metrics["largest_component_size"] <= t["refute_largest_component_max"]
 303:             or metrics["component_count"] >= t["refute_component_count_min"]
 304:         )
 305:     elif sub == "reliability_aware_claim_verification":
 306:         support = (
 307:             metrics["mean_abs_anomaly"] >= t["support_mean_abs_q85"]
 308:             and metrics["mean_completeness"] >= t["support_completeness_p50"]
 309:         )
 310:         refute = metrics["mean_abs_anomaly"] <= t["refute_mean_abs_q50"]
 311:     else:
 312:         raise ValueError(f"Unknown subcategory: {sub}")
 313:
 314:     if support and not refute:
 315:         return "SUPPORTED"
 316:     if refute and not support:
 317:         return "REFUTED"
 318:     if support and refute:
 319:         return "AMBIGUOUS"
 320:     return "INSUFFICIENT"
 321:
 322:
 323: def has_boundary_tie(metrics: dict, protocol: dict) -> bool:
 324:     """Reject examples whose decisive non-degenerate metrics land exactly on a threshold."""
 325:     sub = protocol["subcategory"]
 326:     t = protocol["thresholds"]
 327:     pairs = {
 328:         "persistent_regional_anomaly_verification": [
 329:             ("min_yearly_mean_abs_anomaly", "support_mean_abs_p75"),
 330:             ("min_yearly_mean_abs_anomaly", "refute_mean_abs_p50"),
 331:             ("min_fraction_cells_above_p75", "support_fraction_above_p75"),
 332:         ],
 333:         "localized_intensification_verification": [
 334:             ("regional_abs_anomaly_change", "support_regional_change_q60"),
 335:             ("regional_abs_anomaly_change", "refute_regional_change_q25"),
 336:             ("localized_contrast_change", "support_contrast_change_q75"),
 337:             ("localized_contrast_change", "refute_contrast_change_q25"),
 338:             ("regional_rainfall_change", "support_rainfall_change_q60"),
 339:             ("regional_rainfall_change", "refute_rainfall_change_q25"),
 340:         ],
 341:         "wet_anomaly_consistency_verification": [
 342:             ("mean_signed_anomaly_later_year", "support_signed_anomaly_p75"),
 343:             ("mean_signed_anomaly_later_year", "refute_signed_anomaly_p25"),
 344:             ("regional_rainfall_change", "support_rainfall_change_q75"),
 345:             ("regional_rainfall_change", "refute_rainfall_change_q25"),
 346:             ("fraction_cells_rainfall_increased", "support_fraction_increase_q75"),
 347:             ("fraction_cells_rainfall_increased", "refute_fraction_increase_q25"),
 348:         ],
 349:         "compound_state_transition_verification": [
 350:             ("regional_rainfall_change", "support_rainfall_change_q66"),
 351:             ("regional_rainfall_change", "refute_rainfall_change_q33"),
 352:             ("regional_temperature_change", "support_temperature_change_q66"),
 353:             ("regional_temperature_change", "refute_temperature_change_q33"),
 354:         ],
 355:         "spatial_coherence_verification": [
 356:             ("active_cell_count", "support_active_count_min"),
 357:             ("active_cell_count", "refute_active_count_max"),
 358:             ("largest_component_size", "support_largest_component_min"),
 359:             ("largest_component_size", "refute_largest_component_max"),
 360:             ("component_count", "support_component_count_max"),
 361:             ("component_count", "refute_component_count_min"),
 362:         ],
 363:         "reliability_aware_claim_verification": [
 364:             ("mean_abs_anomaly", "support_mean_abs_q85"),
 365:             ("mean_abs_anomaly", "refute_mean_abs_q50"),
 366:         ],
 367:     }[sub]
 368:     for metric_key, threshold_key in pairs:
 369:         if abs(float(metrics[metric_key]) - float(t[threshold_key])) <= 1e-9:
 370:             return True
 371:     return False
 372:
 373:
 374: def decision_options(decision: str, reason: str, distractor_reasons: dict, seed: int):
 375:     correct = f"{decision} - {reason}"
 376:     labels = ["SUPPORTED", "REFUTED", "INSUFFICIENT"]
 377:     distractors = []
 378:     for label in labels:
 379:         if label == decision:
 380:             continue

In [52]:
import sys
sys.path.append("../src")

In [53]:
from hypothesis_benchmark_generator_v2 import classify_with_thresholds

In [55]:
import json
import pandas as pd

from hypothesis_benchmark_generator_v2 import classify_with_thresholds

with open("../benchmark/ClimateTwinBench_Hypothesis_V2.json","r") as f:
    bench=json.load(f)

questions=bench["questions"]

In [56]:
results=[]

for q in questions:

    ctx=q["context"]

    pred=classify_with_thresholds(

        ctx["metrics"],
        ctx["protocol"]

    )

    results.append({

        "id":q["id"],
        "stored":ctx["decision"],
        "predicted":pred,
        "match":pred==ctx["decision"]

    })

df=pd.DataFrame(results)

display(df.head())

print()

print("Accuracy:",
      df["match"].mean()*100)

        id     stored  predicted  match
0  HYP-001  SUPPORTED  SUPPORTED   True
1  HYP-002  SUPPORTED  SUPPORTED   True
2  HYP-003  SUPPORTED  SUPPORTED   True
3  HYP-004  SUPPORTED  SUPPORTED   True
4  HYP-005  SUPPORTED  SUPPORTED   True

Accuracy: 100.0

In [57]:
errors=df[df["match"]==False]

print("Errors:",len(errors))

display(errors)

Errors: 0

Empty DataFrame
Columns: [id, stored, predicted, match]
Index: []

In [1]:
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [5]:
import os

print(os.getcwd())

e:\ClimateTwinIndia\notebooks

In [7]:
import os

os.listdir()

['01_imd_exploration.ipynb',
 '02_v1_v2_analysis.ipynb',
 '03_temporal_analysis.ipynb',
 '05_derivation_analysis.ipynb',
 '09_derivation_api.ipynb',
 'benchmark.json',
 'benchmark_prompt.txt',
 'climatetwinbench_notebook.ipynb',
 'climatetwinbench_notebook_V2.ipynb',
 'docs',
 'evaluate_hypothesis.ipynb',
 'openrouter_evaluation.ipynb']

In [11]:
claude = pd.read_csv(
    "../experiments/experiment_05_derivation/results/claude_derivation.csv"
)

deepseek = pd.read_csv(
    "../experiments/experiment_05_derivation/results/deepseek_derivation.csv"
)

gpt = pd.read_csv(
    "../experiments/experiment_05_derivation/results/gpt_derivation.csv"
)

In [12]:
def category_accuracy(df):

    return (
        df.groupby("subcategory")
          .apply(
              lambda x: (
                  x["RecoveredDecision"] ==
                  x["GT_Decision"]
              ).mean()*100,
              include_groups=False
          )
          .reset_index(name="Accuracy")
    )

In [13]:
claude_cat = category_accuracy(claude)
deepseek_cat = category_accuracy(deepseek)
gpt_cat = category_accuracy(gpt)

In [14]:
table = (
    claude_cat
    .merge(
        deepseek_cat,
        on="subcategory",
        suffixes=("_Claude", "_DeepSeek")
    )
    .merge(
        gpt_cat,
        on="subcategory"
    )
)

table.rename(
    columns={
        "Accuracy":"Accuracy_GPT"
    },
    inplace=True
)

table

,subcategory,Accuracy_Claude,Accuracy_DeepSeek,Accuracy_GPT
0,compound_state_transition_verification,100.0,100.000000,27.5
1,localized_intensification_verification,100.0,100.000000,45.0
2,persistent_regional_anomaly_verification,100.0,100.000000,100.0
3,reliability_aware_claim_verification,100.0,94.871795,30.0
4,spatial_coherence_verification,100.0,97.500000,32.5
5,wet_anomaly_consistency_verification,100.0,100.000000,27.5

In [16]:
table.to_csv(
    "../experiments/experiment_05_derivation/results/category_accuracy.csv",
    index=False
)

In [17]:
deepseek[
    deepseek["RecoveredDecision"] != deepseek["GT_Decision"]
][[
    "id",
    "subcategory",
    "GT_Decision",
    "RecoveredDecision"
]]

,id,subcategory,GT_Decision,RecoveredDecision
185,HYP-186,spatial_coherence_verification,REFUTED,INSUFFICIENT
212,HYP-213,reliability_aware_claim_verification,SUPPORTED,REFUTED
225,HYP-226,reliability_aware_claim_verification,REFUTED,INSUFFICIENT

In [18]:
failures = deepseek[
    deepseek["RecoveredDecision"] != deepseek["GT_Decision"]
]

failures

,id,subcategory,GT_Decision,Pred_Decision,protocol,Metric_Name1,GT_Metric1,Pred_Metric1,Metric_Name2,GT_Metric2,Pred_Metric2,Metric_Name3,GT_Metric3,Pred_Metric3,RecoveredDecision,Decision_Correct
185,HYP-186,spatial_coherence_verification,REFUTED,NaN,{'subcategory': 'spatial_coherence_verificatio...,active_cell_count,4.0000,2.0000,largest_component_size,1.0,2.0,component_count,4.0,1.0,INSUFFICIENT,False
212,HYP-213,reliability_aware_claim_verification,SUPPORTED,NaN,{'subcategory': 'reliability_aware_claim_verif...,mean_abs_anomaly,1.5182,0.3489,mean_completeness,1.0,1.0,NaN,NaN,NaN,REFUTED,False
225,HYP-226,reliability_aware_claim_verification,REFUTED,NaN,{'subcategory': 'reliability_aware_claim_verif...,mean_abs_anomaly,0.2557,0.4970,mean_completeness,1.0,1.0,NaN,NaN,NaN,INSUFFICIENT,False

In [20]:
import os

for root, dirs, files in os.walk(".."):
    for f in files:
        if "claude" in f.lower() and f.endswith(".csv"):
            print(os.path.join(root, f))

..\experiments\experiment_05_derivation\results\claude_confusion.csv
..\experiments\experiment_05_derivation\results\claude_derivation.csv
..\experiments\experiment_05_derivation\results\claude_metric_summary.csv

In [21]:
import os

for root, dirs, files in os.walk(".."):
    for f in files:
        if "deepseek" in f.lower() and f.endswith(".csv"):
            print(os.path.join(root, f))

..\experiments\experiment_05_derivation\results\deepseek_confusion.csv
..\experiments\experiment_05_derivation\results\deepseek_derivation.csv
..\experiments\experiment_05_derivation\results\deepseek_metric_summary.csv

In [22]:
import os

for root, dirs, files in os.walk("../"):
    for f in files:
        if "v2" in f.lower() and (f.endswith(".py") or f.endswith(".ipynb")):
            print(os.path.join(root, f))

../notebooks\02_v1_v2_analysis.ipynb
../notebooks\climatetwinbench_notebook_V2.ipynb
../src\domain_reasoning_v2.py
../src\hypothesis_benchmark_generator_v2.py

In [23]:
import os

for root, dirs, files in os.walk("../"):
    for f in files:
        if "evaluate" in f.lower():
            print(os.path.join(root, f))

../experiments\experiment_05_derivation\evaluate_derivation.py
../notebooks\evaluate_hypothesis.ipynb